{
  "hash": "85bb38857214436768b1447d23013578",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Lab 03 -- Exploring and visualising data\nembed-resources: true\ntoc-depth: 2\nresources:\n  - data/pie_crab.csv\n  - data/hbr_maples.csv\nexecute: \n  cache: true\n---\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.callout-tip}\n## Learning outcomes\n\nAt the end of this computer practical, students should be able to:\n\n- [ ] Import and prepare data for visualisation\n- [ ] Create basic plot types using ggplot2 (histograms, boxplots, bar plots, scatterplots)\n- [ ] Customise plots with appropriate labels, colours, and themes\n- [ ] Identify and visualise distribution properties (normality, skewness, kurtosis)\n- [ ] Interpret visualisations to draw meaningful conclusions\n- [ ] Export and save plots for reports\n:::\n\n## Before we begin\n\nFor this lab, you will need to:\n\n1. Create a new Quarto document in your **project folder** (or create a new RStudio project) to simplify file management and reproducibility\n2. Download the data files from the links provided in Exercise 1\n3. Make sure you have the following packages installed and loaded:\n   - `tidyverse`: For data manipulation and visualization (includes `ggplot2`)\n   - `moments`: For calculating skewness and kurtosis\n   - `patchwork`: For combining multiple plots\n\nYou can install packages using `install.packages(\"package_name\")` if needed, and load them with `library(package_name)`.\n\n\n## Exercise 1: Dataset exploration\n\n### Exploring the `pie_crab` dataset\n\nIn this lab, we'll work with two environmental datasets. They can be downloaded from the links below:\n\n- [pie_crab.csv](data/pie_crab.csv): Crab size measurements across different sites and latitudes\n- [hbr_maples.csv](data/hbr_maples.csv): Maple seedling measurements from different watersheds\n\nBy now, you should know how to use `read_csv()` to read these datasets into R. If you need a refresher, refer to the previous labs or ask for help from a demonstrator (if available).\n\nLet's start by exploring the `pie_crab` dataset. We've done this before, but it's always good to refresh our memory as these functions are extremely common to use. \n\n- The `str()` function shows us the structure of the dataset, including variable names, types, and a preview of the values.\n- The `head()` function shows the first six rows of the dataset, giving us a quick look at the data.\n- The `summary()` function provides descriptive statistics for each variable, including minimum, maximum, mean, and quartiles for numeric variables.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(pie_crab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [392 × 9] (S3: tbl_df/tbl/data.frame)\n $ date         : Date[1:392], format: \"2016-07-24\" \"2016-07-24\" ...\n $ latitude     : num [1:392] 30 30 30 30 30 30 30 30 30 30 ...\n $ site         : chr [1:392] \"GTM\" \"GTM\" \"GTM\" \"GTM\" ...\n $ size         : num [1:392] 12.4 14.2 14.5 12.9 12.4 ...\n $ air_temp     : num [1:392] 21.8 21.8 21.8 21.8 21.8 ...\n $ air_temp_sd  : num [1:392] 6.39 6.39 6.39 6.39 6.39 ...\n $ water_temp   : num [1:392] 24.5 24.5 24.5 24.5 24.5 ...\n $ water_temp_sd: num [1:392] 6.12 6.12 6.12 6.12 6.12 ...\n $ name         : chr [1:392] \"Guana Tolomoto Matanzas NERR\" \"Guana Tolomoto Matanzas NERR\" \"Guana Tolomoto Matanzas NERR\" \"Guana Tolomoto Matanzas NERR\" ...\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(pie_crab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  date       latitude site   size air_temp air_temp_sd water_temp water_temp_sd\n  <date>        <dbl> <chr> <dbl>    <dbl>       <dbl>      <dbl>         <dbl>\n1 2016-07-24       30 GTM    12.4     21.8        6.39       24.5          6.12\n2 2016-07-24       30 GTM    14.2     21.8        6.39       24.5          6.12\n3 2016-07-24       30 GTM    14.5     21.8        6.39       24.5          6.12\n4 2016-07-24       30 GTM    12.9     21.8        6.39       24.5          6.12\n5 2016-07-24       30 GTM    12.4     21.8        6.39       24.5          6.12\n6 2016-07-24       30 GTM    13.0     21.8        6.39       24.5          6.12\n# ℹ 1 more variable: name <chr>\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(pie_crab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      date               latitude         site                size      \n Min.   :2016-07-24   Min.   :30.00   Length:392         Min.   : 6.64  \n 1st Qu.:2016-07-28   1st Qu.:34.00   Class :character   1st Qu.:12.02  \n Median :2016-08-01   Median :39.10   Mode  :character   Median :14.44  \n Mean   :2016-08-02   Mean   :37.69                      Mean   :14.66  \n 3rd Qu.:2016-08-09   3rd Qu.:41.60                      3rd Qu.:17.34  \n Max.   :2016-08-13   Max.   :42.70                      Max.   :23.43  \n    air_temp      air_temp_sd      water_temp    water_temp_sd  \n Min.   :10.29   Min.   :6.391   Min.   :13.98   Min.   :4.838  \n 1st Qu.:12.05   1st Qu.:8.110   1st Qu.:14.33   1st Qu.:6.567  \n Median :13.93   Median :8.410   Median :17.50   Median :6.998  \n Mean   :15.20   Mean   :8.654   Mean   :17.65   Mean   :7.252  \n 3rd Qu.:18.63   3rd Qu.:9.483   3rd Qu.:20.54   3rd Qu.:7.865  \n Max.   :21.79   Max.   :9.965   Max.   :24.50   Max.   :9.121  \n     name          \n Length:392        \n Class :character  \n Mode  :character  \n                   \n                   \n                   \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.callout-tip}\n## Question 1\nWhat variables are in the dataset? What are the data types of each variable? Are there any missing values? What are the ranges of the numeric variables?\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.callout-warning}\n## Answer 1\nFrom our exploration of the pie_crab dataset, we can see that:\n\n- **What variables are in the dataset?** The dataset contains 9 variables: date, latitude, site, size, air_temp, air_temp_sd, water_temp, water_temp_sd, and name\n- **What are the data types of each variable?** Data types:\n  - `date`: Date format\n  - `latitude`, `size`, `air_temp`, `air_temp_sd`, `water_temp`, `water_temp_sd`: numeric variables\n  - `site`, `name`: character variables (which we'll later convert to factors)\n- **Are there any missing values?** Based on the summary output there are no missing values\n- **What are the ranges of the numeric variables?**\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# We can answer this question by viewing the numbers in `summmary()`\n# but, we can compute it too. See ?sapply for more information\nsapply(pie_crab[, sapply(pie_crab, is.numeric)], range)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     latitude  size air_temp air_temp_sd water_temp water_temp_sd\n[1,]     30.0  6.64   10.293       6.391     13.976         4.838\n[2,]     42.7 23.43   21.792       9.965     24.502         9.121\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n- Ranges of numeric variables:\n  - latitude: 30.00 to 42.70 degrees\n  - size: 6.64 to 23.43 mm\n  - air_temp: 10.29 to 21.79 °C\n  - water_temp: 13.98 to 24.50 °C\n  - air_temp_sd: 6.39 to 9.97\n  - water_temp_sd: 4.84 to 9.12\n:::\n:::\n\nFrom our exploration, we can see that the pie_crab dataset contains information about:\n\n- `date`: When the crabs were measured\n- `latitude`: The latitude where the crabs were collected\n- `site`: The specific collection site\n- `size`: The size of the crabs in millimeters\n- `air_temp`: Air temperature in degrees Celsius\n- `water_temp`: Water temperature in degrees Celsius\n\n### Identifying factors in the data\n\nOne of the first steps in data exploration is to determine if your data types are recognised correctly by R. Looking at the output of `str()` can help you identify variables that might be better represented as different data types.\n\nIn our dataset, `site` and `name` are character variables with repeating values. When categorical variables like these have a limited number of possible values that repeat throughout the dataset, they're good candidates to be converted to factors. Factors are R's way of representing categorical data efficiently.\n\nWe can check how many unique values these variables have using the `unique()` function:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(pie_crab$site)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"GTM\" \"SI\"  \"NIB\" \"ZI\"  \"RC\"  \"VCR\" \"DB\"  \"JC\"  \"CT\"  \"NB\"  \"CC\"  \"BC\" \n[13] \"PIE\"\n```\n\n\n:::\n\n```{.r .cell-code}\nunique(pie_crab$name)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Guana Tolomoto Matanzas NERR\"     \"Sapelo Island NERR\"              \n [3] \"North Inlet Winyah Bay NERR\"      \"Zeke's Island NERR\"              \n [5] \"Rachel Carson NERR\"               \"Virginia Coastal Reserve LTER\"   \n [7] \"Delaware Bay NERR\"                \"Jacques Cousteau NERR\"           \n [9] \"Sixpenny Island - Connecticut\"    \"Narragansett Bay NERR\"           \n[11] \"Cape Cod\"                         \"Bare Cove Park\"                  \n[13] \"Plum Island Estuary - West Creek\"\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nFor a dataset with 392 observations, having only a few unique sites and names suggests that these variables should be factors. Let's count exactly how many unique values we have:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlength(unique(pie_crab$site))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(unique(pie_crab$name))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nWe can convert these character variables to factors using the `factor()` function:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert site and name to factors\npie_crab$site <- factor(pie_crab$site)\npie_crab$name <- factor(pie_crab$name)\n\n# Check the structure again to confirm the conversion\nstr(pie_crab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [392 × 9] (S3: tbl_df/tbl/data.frame)\n $ date         : Date[1:392], format: \"2016-07-24\" \"2016-07-24\" ...\n $ latitude     : num [1:392] 30 30 30 30 30 30 30 30 30 30 ...\n $ site         : Factor w/ 13 levels \"BC\",\"CC\",\"CT\",..: 5 5 5 5 5 5 5 5 5 5 ...\n $ size         : num [1:392] 12.4 14.2 14.5 12.9 12.4 ...\n $ air_temp     : num [1:392] 21.8 21.8 21.8 21.8 21.8 ...\n $ air_temp_sd  : num [1:392] 6.39 6.39 6.39 6.39 6.39 ...\n $ water_temp   : num [1:392] 24.5 24.5 24.5 24.5 24.5 ...\n $ water_temp_sd: num [1:392] 6.12 6.12 6.12 6.12 6.12 ...\n $ name         : Factor w/ 13 levels \"Bare Cove Park\",..: 4 4 4 4 4 4 4 4 4 4 ...\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nNotice how we've converted the specific variables to factors and used the assignment operator `<-` to update the dataset. This is a common pattern in R, where we update the dataset in place. The output of `str()` now shows these variables as factors with their levels (unique values) listed.\n\nConverting to factors is important because:\n\n1. It makes R treat the data appropriately in statistical analyses\n2. It can make visualizations more informative\n3. It improves memory efficiency for large datasets\n\n\n## Exercise 2: Building visualizations with `ggplot2`\n\n### The grammar of graphics\n\nThe ggplot2 package is based on the \"grammar of graphics,\" a framework that breaks visualisations into components, similar to how grammar breaks language into parts of speech. This approach makes it possible to create complex visualisations by combining simple elements.\n\nThe key components (or layers) include:\n\n- **Data**: The dataset being visualised\n- **Aesthetics**: Mappings from data variables to visual properties\n- **Geometries**: The shapes used to represent the data\n- **Facets**: Subplots that show different subsets of the data\n- **Statistics**: Transformations of the data (e.g., counts, means)\n- **Coordinates**: The space in which the data is plotted\n- **Themes**: Visual styling of non-data elements\n\nLet's learn how to create visualisations using this approach by building a plot step by step, explaining each component along the way. **As you follow along, you are improving the code that produces the plot -- not re-writing it -- at each step.**\n\n### Step 1: The canvas\n\nEvery ggplot2 visualisation starts with a blank canvas:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Start with an empty canvas\nggplot()\n```\n\n::: {.cell-output-display}\n![](Lab03_files/figure-typst/unnamed-chunk-6-1.svg)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nThis creates an empty plotting space. It doesn't show anything yet because we haven't specified any data or how to visualise it.\n\n### Step 2: Adding data\n\nNext, we tell ggplot2 what data to use. Ideally the data is a `data.frame` or `tibble` object (which you will know by using `str()` previously):\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add data to the plot\nggplot(data = pie_crab)\n```\n\n::: {.cell-output-display}\n![](Lab03_files/figure-typst/unnamed-chunk-7-1.svg)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nWe've now told ggplot2 to use the `pie_crab` dataset, but we still cannot see anything because we have not specified which variables to plot -- or how to represent them.\n\n### Step 3: Mapping aesthetics\n\nAesthetics map variables in your data to visual properties in the plot. They are a function `aes()` on their own. Think of aesthetics as how you woul define `x`, `y` and other dimensions in the plot.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Map variables to visual properties\nggplot(data = pie_crab, mapping = aes(x = size))\n```\n\n::: {.cell-output-display}\n![](Lab03_files/figure-typst/unnamed-chunk-8-1.svg)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nHere, we've mapped the `size` variable to the x-axis. This variable is something that exists in the `pie_crab` data frame. We still cannot see any data points because we haven't specified how to represent the data (e.g., as points, bars, or lines).\n\n### Step 4: Adding a Geometry\n\nGeometries determine how the data is represented visually. They are functions that are prefixed by `geom_*` so that users know what they are meant to do. In most cases it is clear what type of plot is being create by reading the name of the geometry function(s) in the plot code.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add a histogram geometry\nggplot(data = pie_crab, mapping = aes(x = size)) +\n  geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Lab03_files/figure-typst/unnamed-chunk-9-1.svg)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nNow we can see the data! We've added a histogram geometry (`geom_histogram()`), which counts the number of observations falling into bins along the x-axis. The `+` operator adds layers to the plot.\n\nNotice the message about the default bin width. ggplot2 automatically chose 30 bins, but we can adjust this.\n\n### Step 5: Customizing the Geometry\n\nLet's customize our histogram:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Customize the histogram\nggplot(data = pie_crab, mapping = aes(x = size)) +\n  geom_histogram(bins = 20, fill = \"skyblue\", color = \"black\")\n```\n\n::: {.cell-output-display}\n![](Lab03_files/figure-typst/unnamed-chunk-10-1.svg)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nWe've made several changes:\n\n- `bins = 20`: Changed the number of bins to 20\n- `fill = \"skyblue\"`: Set the fill color of the bars to sky blue\n- `color = \"black\"`: Set the outline color of the bars to black\n\nThese are fixed properties applied to all bars, not mappings from data variables. For colours you may search \"r colours\" in your web browser to see what available colours you can use (it's a *lot*).\n\n### Step 6: Adding Labels and Titles\n\nGood visualisations have clear labels. Titles are optional -- but the option is available if you need it. We can add all of these in the next layer using the `labs()` function: \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add informative labels\nggplot(data = pie_crab, mapping = aes(x = size)) +\n  geom_histogram(bins = 20, fill = \"skyblue\", color = \"black\") +\n  labs(\n    title = \"Distribution of Crab Sizes\",\n    x = \"Size (mm)\",\n    y = \"Count\"\n  )\n```\n\n::: {.cell-output-display}\n![](Lab03_files/figure-typst/unnamed-chunk-11-1.svg)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nThe `labs()` function adds various text elements to the plot:\n\n- `title`: The main title of the plot\n- `x`: The x-axis label\n- `y`: The y-axis label\n\n### Step 7: Applying a Theme\n\nThemes control the overall appearance of the plot:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add a theme for consistent styling\nggplot(data = pie_crab, mapping = aes(x = size)) +\n  geom_histogram(bins = 20, fill = \"skyblue\", color = \"black\") +\n  labs(\n    title = \"Distribution of Crab Sizes\",\n    x = \"Size (mm)\",\n    y = \"Count\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Lab03_files/figure-typst/unnamed-chunk-12-1.svg)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nThe `theme_minimal()` function applies a minimalist theme with a white background and subtle grid lines. Other common themes include:\n\n- `theme_classic()`: No grid lines, simple axes\n- `theme_light()`: Light background with subtle grid lines\n- `theme_dark()`: Dark background for presentations\n\n### Bonus: Adding multiple geometries\n\nOne of the powerful features of ggplot2 is the ability to layer multiple geometries:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add a density curve on top of the histogram\nggplot(data = pie_crab, mapping = aes(x = size)) +\n  geom_histogram(aes(y = after_stat(density)),\n    bins = 20,\n    fill = \"skyblue\", color = \"black\"\n  ) +\n  geom_density(color = \"red\", linewidth = 1) +\n  labs(\n    title = \"Distribution of Crab Sizes\",\n    x = \"Size (mm)\",\n    y = \"Density\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Lab03_files/figure-typst/unnamed-chunk-13-1.svg)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nIn this plot:\n\n- We've changed the y-axis of the histogram to show density instead of count using `aes(y = after_stat(density))`\n- We've added a density curve with `geom_density()`\n- We've set the density curve color to red and increased its line width\n\n::: {.callout-tip}\n## Question 2\n\n1. What's the difference between setting a fixed property (like `fill = \"blue\"`) and mapping a variable to an aesthetic (like `aes(fill = site)`)?\n2. How would you modify the histogram to have more or fewer bins? Use `?geom_histogram` to help you think of an answer.\n3. What would happen if you changed the order of the `geom_histogram()` and `geom_density()` layers?\n:::\n\n::: {.column-margin}\nThese questions can typically be answered by making changes to the code to view the differences.\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.callout-warning}\n## Answer 2\n\n1. **Fixed property vs. aesthetic mapping**:\n   - Fixed property (e.g., `fill = \"blue\"`): Applies the same value to all elements, regardless of data values\n   - Aesthetic mapping (e.g., `aes(fill = site)`): Maps a variable in your data to a visual property, creating different values based on the data\n   - Fixed properties are used for consistent styling, while aesthetic mappings are used to represent data values visually\n\n2. **Modifying histogram bins**:\n   - To change the number of bins: Use the `bins` parameter (e.g., `geom_histogram(bins = 30)`)\n   - To specify bin width directly: Use the `binwidth` parameter (e.g., `geom_histogram(binwidth = 2)`)\n   - Fewer bins show broader patterns but less detail, while more bins show more detail but may be noisier\n\n3. **Changing layer order**:\n   - If `geom_density()` came before `geom_histogram()`, the histogram would be drawn on top of the density curve\n   - This would make the density curve partially or completely hidden behind the histogram\n   - Layer order matters because layers are drawn in the order they are added, with later layers appearing on top\n:::\n:::\n\n## Exercise 3: Analysing environmental variables\n\nNow that we understand the grammar of graphics approach, let's analyse a different variable in our dataset.\n\n### Examining water temperature distribution\n\nLet's examine the distribution of water temperatures across our sampling sites:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a basic histogram of water temperatures\nggplot(pie_crab, aes(x = water_temp)) +\n  geom_histogram(bins = 15) +\n  labs(\n    title = \"Distribution of Water Temperatures\",\n    x = \"Water Temperature (°C)\",\n    y = \"Count\"\n  )\n```\n\n::: {.cell-output-display}\n![](Lab03_files/figure-typst/unnamed-chunk-14-1.svg)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nThe histogram shows us the frequency distribution of water temperatures. We can see the shape of the distribution, including any skewness or unusual patterns.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add a density curve\nggplot(pie_crab, aes(x = water_temp)) +\n  geom_histogram(aes(y = after_stat(density)),\n    bins = 15,\n    fill = \"lightblue\", colour = \"black\"\n  ) +\n  geom_density(colour = \"red\") +\n  labs(\n    title = \"Distribution of Water Temperatures\",\n    x = \"Water Temperature (°C)\",\n    y = \"Density\"\n  )\n```\n\n::: {.cell-output-display}\n![](Lab03_files/figure-typst/unnamed-chunk-15-1.svg)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nAdding a density curve helps us see the overall shape of the distribution more clearly.\n\n::: {.callout-tip}\n## Question 3\nWhat is the shape of the distribution of water temperatures? Does the distribution appear to be normal? Are there any outliers? \n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.callout-warning}\n## Answer 3\nBased on the histogram and density plot of water temperatures:\n\n- **Shape of the distribution**: The distribution appears to be right-skewed (positively skewed), with a longer tail extending toward higher temperatures. The data also appears to be bimodal, although there are gaps that make it a bit harder to assert tha this is the case.\n\n- **Normality**: The distribution does not appear to be perfectly normal. A normal distribution would be symmetric around the mean, but this distribution shows some asymmetry. The density curve helps visualize this deviation from normality.\n\n- **Outliers**: There appear to be a few potential outliers on the right side of the distribution, representing unusually warm water temperatures. Outliers are (often) isolated bars in the histogram at the right end of the distribution.\n:::\n:::\n\n### Skewness and Kurtosis\n\nTo quantify the shape of the water temperature distribution, we can calculate skewness and kurtosis:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate skewness and kurtosis for water temperature\nskewness_value <- skewness(pie_crab$water_temp)\nkurtosis_value <- kurtosis(pie_crab$water_temp)\nskewness_value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4750277\n```\n\n\n:::\n\n```{.r .cell-code}\nkurtosis_value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.888369\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n**Interpreting these values:**\n\n- **Skewness** measures the asymmetry of the distribution:\n\n  - 0 = symmetric (like a normal distribution)\n  - More than, > 0 = right-skewed (tail extends to the right)\n  - Less than, < 0 = left-skewed (tail extends to the left)\n\n- **Kurtosis** measures the \"tailedness\" of the distribution:\n\n  - 3 = normal distribution (in the `moments` package, this is sometimes normalized to 0)\n  - More than, > 3 = leptokurtic (heavy-tailed, more outliers)\n  - Less than, < 3 = platykurtic (light-tailed, fewer outliers)\n\nThe skewness value of approximately 0.5 confirms our visual observation that the water temperature distribution is moderately right-skewed. The kurtosis value of approximately 2.5 indicates the distribution has slightly lighter tails than a normal distribution.\n\nThese numerical measures help us quantify what we observe visually in the histograms and density plots. Now that we understand the overall distribution of our data, let's explore how it varies across different groups.\n\n## Exercise 4: Comparing groups\n\nNow that we've examined the overall distribution of crab sizes, let's compare sizes across different groups.\n\n### Creating boxplots to compare sites\n\nBoxplots are excellent for comparing distributions between two or more groups:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create boxplots of crab sizes by site\nggplot(pie_crab, aes(x = site, y = size)) +\n  geom_boxplot(fill = \"skyblue\") +\n  labs(\n    title = \"Crab Sizes by Site\",\n    x = \"Site\",\n    y = \"Size (mm)\"\n  )\n```\n\n::: {.cell-output-display}\n![](Lab03_files/figure-typst/unnamed-chunk-17-1.svg)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nA boxplot shows:\n\n- The median (middle line)\n- The interquartile range (IQR) from the 25th to 75th percentile (the box)\n- The whiskers (typically extend to 1.5 × IQR)\n- Outliers (points beyond the whiskers)\n\nTo see the actual data points alongside the boxplots we can add another geometric layer. You can see how it may or may not be useful to readers. In most cases adding the data points is **not** necessary, but in some cases it could be useful in the exploration phase (i.e. not the final plot for publication).\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add points to see the actual data\nggplot(pie_crab, aes(x = site, y = size)) +\n  geom_boxplot(fill = \"skyblue\", alpha = 0.5) +\n  geom_jitter(width = 0.2, alpha = 0.5) +\n  labs(\n    title = \"Crab Sizes by Site\",\n    x = \"Site\",\n    y = \"Size (mm)\"\n  )\n```\n\n::: {.cell-output-display}\n![](Lab03_files/figure-typst/unnamed-chunk-18-1.svg)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nWe've added:\n\n- `geom_jitter()` to add individual data points with a slight horizontal jitter to avoid overplotting\n- `alpha = 0.5` to make both the boxplots and points semi-transparent\n- `width = 0.2` to control the amount of horizontal jittering\n\n::: {.callout-tip}\n## Question 4\nHow do crab sizes vary across different sites? Which site has the largest median crab size? Which site shows the most variability in crab sizes? Are there any outliers at specific sites? Answer these questions in a descriptive manner using the plot.\n:::\n\n::: {.column-margin}\nHere we are exercising our ability to see patterns from data visualisations and using them to make certain observations about the data.\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.callout-warning}\n## Answer 4\nBased on the boxplots comparing crab sizes across different sites:\n\n- **Variation across sites**: There is considerable variation in crab sizes between sites.\n\n- **Largest median size**: PIE (Plum Island Estuary) has the largest median crab size since the median line is the highest among the different boxplots.\n\n- **Most variability**: BC (Bare Cove Park) shows the most variability in crab sizes. This is evidenced by its wider box and longer whiskers in the boxplot, indicating a broader spread of sizes.\n\n- **Outliers**: Yes, there are outliers at specific sites. Several sites show individual points above or below their whiskers, representing unusually large or small crabs for those locations. These outliers are important to note as they may represent unique environmental conditions or genetic factors affecting growth.\n:::\n:::\n\n### Exploring the relationship between latitude and size\n\nLet's examine if there's a relationship between latitude and crab size:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a scatterplot of size vs. latitude\nggplot(pie_crab, aes(x = latitude, y = size)) +\n  geom_point(alpha = 0.5) +\n  labs(\n    title = \"Crab Size vs. Latitude\",\n    x = \"Latitude\",\n    y = \"Size (mm)\"\n  )\n```\n\n::: {.cell-output-display}\n![](Lab03_files/figure-typst/unnamed-chunk-19-1.svg)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nScatterplots show the relationship between two continuous variables. Each point represents a single observation.\n\nTo help visualise the trend, we can add a trend line (something that we will cover in greater detail once we look at linear models in Week 7):\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add a trend line\nggplot(pie_crab, aes(x = latitude, y = size)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(method = \"lm\", se = TRUE) +\n  labs(\n    title = \"Crab Size vs. Latitude\",\n    x = \"Latitude\",\n    y = \"Size (mm)\"\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Lab03_files/figure-typst/unnamed-chunk-20-1.svg)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nWe've added:\n\n- `geom_smooth(method = \"lm\")` to add a linear regression line\n- `se = TRUE` to include the standard error as a shaded confidence band\n\n::: {.callout-tip}\n## Question 5\nIs there a relationship between latitude and crab size?\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.callout-warning}\n## Answer 5\nBased on the scatterplot it looks like as latitude increases, size also increases, because the trend line shows a general positive trend.\n:::\n:::\n\n## Exercise 5: Faceting and grouping\n\nSo far, we've created separate plots for different analyses. Now, let's explore techniques for comparing multiple groups or variables within a single plot.\n\n### Exploring the `hbr_maples` dataset\n\nLet's switch to our second dataset, which contains measurements of maple seedlings from different watersheds:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Examine the structure of the maples dataset\nstr(hbr_maples)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [359 × 11] (S3: tbl_df/tbl/data.frame)\n $ year               : num [1:359] 2003 2003 2003 2003 2003 ...\n $ watershed          : Factor w/ 2 levels \"Reference\",\"W1\": 1 1 1 1 1 1 1 1 1 1 ...\n $ elevation          : Factor w/ 2 levels \"Low\",\"Mid\": 1 1 1 1 1 1 1 1 1 1 ...\n $ transect           : Factor w/ 12 levels \"R1\",\"R2\",\"R3\",..: 1 1 1 1 1 1 1 1 1 1 ...\n $ sample             : Factor w/ 20 levels \"1\",\"2\",\"3\",\"4\",..: 1 2 3 4 5 6 7 8 9 10 ...\n $ stem_length        : num [1:359] 86.9 114 83.5 68.1 72.1 77.7 85.5 81.6 92.9 59.6 ...\n $ leaf1area          : num [1:359] 13.84 14.57 12.45 9.97 6.84 ...\n $ leaf2area          : num [1:359] 12.13 15.27 9.73 10.07 5.48 ...\n $ leaf_dry_mass      : num [1:359] 0.0453 0.0476 0.0423 0.0397 0.0204 0.0317 0.0382 0.0179 0.0286 0.0125 ...\n $ stem_dry_mass      : num [1:359] 0.03 0.0338 0.0248 0.0194 0.018 0.0246 0.0316 0.015 0.0291 0.0149 ...\n $ corrected_leaf_area: num [1:359] 29.1 33 25.3 23.2 15.5 ...\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# View the first few rows\nhead(hbr_maples)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 11\n   year watershed elevation transect sample stem_length leaf1area leaf2area\n  <dbl> <fct>     <fct>     <fct>    <fct>        <dbl>     <dbl>     <dbl>\n1  2003 Reference Low       R1       1             86.9     13.8      12.1 \n2  2003 Reference Low       R1       2            114       14.6      15.3 \n3  2003 Reference Low       R1       3             83.5     12.5       9.73\n4  2003 Reference Low       R1       4             68.1      9.97     10.1 \n5  2003 Reference Low       R1       5             72.1      6.84      5.48\n6  2003 Reference Low       R1       6             77.7      9.66      7.64\n# ℹ 3 more variables: leaf_dry_mass <dbl>, stem_dry_mass <dbl>,\n#   corrected_leaf_area <dbl>\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get a summary of the variables\nsummary(hbr_maples)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      year          watershed   elevation     transect       sample   \n Min.   :2003   Reference:179   Low :120   R1     : 40   1      : 18  \n 1st Qu.:2003   W1       :180   Mid :120   R2     : 40   2      : 18  \n Median :2003                   NA's:119   W1-1   : 40   3      : 18  \n Mean   :2003                              W1-2   : 40   4      : 18  \n 3rd Qu.:2004                              W1-3   : 40   5      : 18  \n Max.   :2004                              R3     : 39   6      : 18  \n                                           (Other):120   (Other):251  \n  stem_length       leaf1area        leaf2area     leaf_dry_mass    \n Min.   : 52.70   Min.   : 2.480   Min.   : 3.40   Min.   :0.01170  \n 1st Qu.: 75.65   1st Qu.: 8.818   1st Qu.: 8.95   1st Qu.:0.03975  \n Median : 85.70   Median :11.636   Median :11.28   Median :0.05590  \n Mean   : 86.86   Mean   :11.800   Mean   :11.75   Mean   :0.06368  \n 3rd Qu.: 97.05   3rd Qu.:14.016   3rd Qu.:14.30   3rd Qu.:0.07855  \n Max.   :132.30   Max.   :26.952   Max.   :25.79   Max.   :0.38700  \n                  NA's   :119      NA's   :119                      \n stem_dry_mass     corrected_leaf_area\n Min.   :0.00790   Min.   : 9.597     \n 1st Qu.:0.02360   1st Qu.:21.180     \n Median :0.03320   Median :25.950     \n Mean   :0.04506   Mean   :26.687     \n 3rd Qu.:0.05820   3rd Qu.:31.751     \n Max.   :0.15000   Max.   :55.874     \n                   NA's   :119        \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nNow, let's create histograms of stem length by watershed using faceting:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create histograms of stem length by watershed\nggplot(hbr_maples, aes(x = stem_length)) +\n  geom_histogram(bins = 20, fill = \"forestgreen\", colour = \"black\") +\n  facet_wrap(~watershed) +\n  labs(\n    title = \"Distribution of Stem Lengths by Watershed\",\n    x = \"Stem Length (mm)\",\n    y = \"Count\"\n  )\n```\n\n::: {.cell-output-display}\n![](Lab03_files/figure-typst/unnamed-chunk-24-1.svg)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nThe `facet_wrap()` function creates separate panels for each value of the specified variable. This allows us to compare distributions across groups.\n\n::: {.callout-tip}\n## Question 6\nHow do stem lengths differ between watersheds? Which watershed shows more variability in stem lengths? Are the distributions similarly shaped? Use only the visualisations to answer these questions.\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.callout-warning}\n## Answer 6\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# check median between watersheds\nmedian(hbr_maples$stem_length[hbr_maples$watershed == \"Reference\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 80.6\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(hbr_maples$stem_length[hbr_maples$watershed == \"W1\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 90\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nBased on the histograms:\n- **Differences between watersheds**: Median stem lengths are higher in W1 compared to the Reference watershed.\n- it appears that the Reference watershed is skewed to the right, whereas W1 is more normally distributed.\n:::\n:::\n\n### Comparing leaf area and stem length\n\nLet's examine the relationship between leaf area and stem length, comparing across watersheds:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a scatterplot of leaf area vs. stem length, coloured by watershed\nggplot(hbr_maples, aes(x = stem_length, y = corrected_leaf_area, colour = watershed)) +\n  geom_point(alpha = 0.7) +\n  labs(\n    title = \"Leaf Area vs. Stem Length\",\n    x = \"Stem Length (mm)\",\n    y = \"Corrected Leaf Area (cm²)\",\n    colour = \"Watershed\"\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 119 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Lab03_files/figure-typst/unnamed-chunk-26-1.svg)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nHere, we've mapped the `watershed` variable to the `colour` aesthetic, which automatically creates a color-coded legend.\n\nLet's add separate trend lines for each watershed:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add separate trend lines for each watershed\nggplot(hbr_maples, aes(x = stem_length, y = corrected_leaf_area, colour = watershed)) +\n  geom_point(alpha = 0.7) +\n  geom_smooth(method = \"lm\", se = FALSE) +\n  labs(\n    title = \"Leaf Area vs. Stem Length\",\n    x = \"Stem Length (mm)\",\n    y = \"Corrected Leaf Area (cm²)\",\n    colour = \"Watershed\"\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 119 rows containing non-finite outside the scale range\n(`stat_smooth()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 119 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Lab03_files/figure-typst/unnamed-chunk-27-1.svg)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nWhen we include `colour = watershed` in the global aesthetics, ggplot2 automatically applies this grouping to all geometries, including `geom_smooth()`. This creates separate trend lines for each watershed.\n\n::: {.callout-tip}\n## Question 7\nIs there a relationship between stem length and leaf area? Does this relationship differ between watersheds? What might explain these differences from an ecological perspective?\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.callout-warning}\n## Answer 7\nBased on the scatterplot examining the relationship between stem length and leaf area:\n\n- **Relationship existence**: Yes, there is a clear positive relationship between stem length and leaf area. As stem length increases, leaf area tends to increase as well. This suggests that larger seedlings generally have both longer stems and larger leaves.\n\n- **Differences between watersheds**: The relationship does differ between watersheds. The trend lines for each watershed have different slopes, indicating that the rate at which leaf area increases with stem length varies. Watershed 6 appears to have a steeper slope than Watershed 1, suggesting that for each unit increase in stem length, seedlings in Watershed 6 gain more leaf area than those in Watershed 1.\n\n- **Ecological explanation**: These differences could be explained by several ecological factors:\n  1. **Resource availability**: Watershed 6 may have more favorable growing conditions (e.g., better soil nutrients, more water, or optimal light conditions) that allow seedlings to allocate more resources to leaf production relative to stem growth.\n  2. **Adaptation to local conditions**: Seedlings in different watersheds may have adapted different growth strategies in response to local environmental pressures.\n  3. **Competition**: Different levels of competition in each watershed might influence how seedlings allocate resources between stem and leaf growth.\n  4. **Genetic differences**: There could be genetic differences between maple populations in different watersheds that influence their growth patterns.\n\nThese findings highlight the importance of considering environmental context when studying plant growth relationships, as the same species can show different growth patterns in different habitats.\n:::\n:::\n\n## Exercise 6: Bonus take-home\n\nThese exercises are designed for you to practice the visualisation techniques we've covered in this lab. You can complete them during the lab if you finish early, or at home for additional practice.\n\n### Basic visualisation practice\n\n1. Create a histogram of the `water_temp` variable in the crabs dataset. Calculate and interpret its skewness and kurtosis.\n2. Create boxplots comparing the `leaf_dry_mass` between watersheds in the maples dataset. What do you observe?\n3. Create a scatterplot examining the relationship between `stem_dry_mass` and `leaf_dry_mass` in the maples dataset, with points coloured by watershed.\n\n\n### Advanced challenge: `patchwork`\n\nThe patchwork package allows you to combine multiple plots into a single figure. This is useful for creating complex visualisations that tell a story about your data.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the patchwork package\nlibrary(patchwork)\n```\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nLet's create a few plots and then combine them:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create multiple plots\np1 <- ggplot(pie_crab, aes(x = size)) +\n  geom_histogram(fill = \"skyblue\", colour = \"black\") +\n  labs(title = \"Distribution of Crab Sizes\")\n\np2 <- ggplot(pie_crab, aes(x = latitude, y = size)) +\n  geom_point() +\n  geom_smooth(method = \"lm\") +\n  labs(title = \"Size vs. Latitude\")\n\np3 <- ggplot(pie_crab, aes(x = site, y = size)) +\n  geom_boxplot(fill = \"skyblue\") +\n  labs(title = \"Size by Site\")\n\n# Combine plots (this is patchwork in action!)\np1 / (p2 + p3)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Lab03_files/figure-typst/unnamed-chunk-29-1.svg)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nThe patchwork syntax is intuitive:\n\n- `/` arranges plots vertically (one above the other)\n- `+` arranges plots horizontally (side by side)\n- You can use parentheses to control the layout\n\nNow, try these exercises:\n\n4. Create a combined plot using patchwork that shows:\n   - A histogram of stem lengths\n   - A scatterplot of stem length vs. leaf area\n   - Boxplots of stem lengths by watershed\n   - Arrange these plots in a 2x2 grid\n\n5. Create a combined plot that tells a story about the relationship between temperature and crab size:\n   - A scatterplot of air temperature vs. crab size\n   - A scatterplot of water temperature vs. crab size\n   - A boxplot of crab sizes by site\n   - Arrange the scatterplots side by side and the boxplot below them\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.callout-warning}\n## Solutions to Take-home Exercises\n\n\n1. Histogram of water temperature with skewness and kurtosis:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create histogram of water temperature\nggplot(pie_crab, aes(x = water_temp)) +\n  geom_histogram(bins = 15, fill = \"lightblue\", color = \"black\") +\n  labs(\n    title = \"Distribution of Water Temperature\",\n    x = \"Water Temperature (°C)\",\n    y = \"Count\"\n  )\n```\n\n::: {.cell-output-display}\n![](Lab03_files/figure-typst/unnamed-chunk-30-1.svg)\n:::\n\n```{.r .cell-code}\n# Calculate skewness and kurtosis\nskew_water <- skewness(pie_crab$water_temp)\nkurt_water <- kurtosis(pie_crab$water_temp)\n\ncat(\"Skewness of water temperature:\", skew_water, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSkewness of water temperature: 0.4750277 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Kurtosis of water temperature:\", kurt_water, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKurtosis of water temperature: 1.888369 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n**Interpretation**: The water temperature distribution has a skewness of approximately 0.5, indicating it is right-skewed (though only moderately). The kurtosis value of approximately 1.89 suggests the distribution is slightly platykurtic (light-tailed) compared to a normal distribution.\n\n2. Boxplots of leaf dry mass by watershed:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create boxplots of leaf dry mass by watershed\nggplot(hbr_maples, aes(x = watershed, y = leaf_dry_mass)) +\n  geom_boxplot(fill = \"lightgreen\") +\n  labs(\n    title = \"Leaf Dry Mass by Watershed\",\n    x = \"Watershed\",\n    y = \"Leaf Dry Mass (g)\"\n  )\n```\n\n::: {.cell-output-display}\n![](Lab03_files/figure-typst/unnamed-chunk-31-1.svg)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n**Observation**: The boxplots show that Watershed 1 has higher median leaf dry mass compared to the reference. \n\n3. Scatterplot of stem dry mass vs. leaf dry mass:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create scatterplot of stem dry mass vs. leaf dry mass\nggplot(hbr_maples, aes(x = stem_dry_mass, y = leaf_dry_mass, color = watershed)) +\n  geom_point(alpha = 0.7) +\n  geom_smooth(method = \"lm\", se = FALSE) +\n  labs(\n    title = \"Relationship Between Stem and Leaf Dry Mass\",\n    x = \"Stem Dry Mass (g)\",\n    y = \"Leaf Dry Mass (g)\",\n    color = \"Watershed\"\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Lab03_files/figure-typst/unnamed-chunk-32-1.svg)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n**Observation**: There appears to be a strong positive relationship between stem dry mass and leaf dry mass, suggesting that seedlings with larger stems also have more leaf mass. \n\n4. Combined plot of stem length visualisations:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create individual plots\np1 <- ggplot(hbr_maples, aes(x = stem_length)) +\n  geom_histogram(fill = \"forestgreen\", color = \"black\") +\n  labs(title = \"Distribution of Stem Lengths\")\n\np2 <- ggplot(hbr_maples, aes(x = stem_length, y = corrected_leaf_area)) +\n  geom_point() +\n  geom_smooth(method = \"lm\") +\n  labs(title = \"Stem Length vs. Leaf Area\")\n\np3 <- ggplot(hbr_maples, aes(x = watershed, y = stem_length)) +\n  geom_boxplot(fill = \"forestgreen\") +\n  labs(title = \"Stem Length by Watershed\")\n\n# Combine the plots\np1 / (p2 + p3)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 119 rows containing non-finite outside the scale range\n(`stat_smooth()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 119 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Lab03_files/figure-typst/unnamed-chunk-33-1.svg)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n5. Combined plot of temperature and crab size:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create individual plots\np1 <- ggplot(pie_crab, aes(x = air_temp, y = size)) +\n  geom_point() +\n  geom_smooth(method = \"lm\") +\n  labs(title = \"Size vs. Air Temperature\")\n\np2 <- ggplot(pie_crab, aes(x = water_temp, y = size)) +\n  geom_point() +\n  geom_smooth(method = \"lm\") +\n  labs(title = \"Size vs. Water Temperature\")\n\np3 <- ggplot(pie_crab, aes(x = site, y = size)) +\n  geom_boxplot(fill = \"skyblue\") +\n  labs(title = \"Size by Site\")\n\n# Combine the plots\n(p1 + p2) / p3\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Lab03_files/figure-typst/unnamed-chunk-34-1.svg)\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n:::\n:::\n\n## Summary\n\nIn this lab, we've explored how to create and customize various types of visualisations using ggplot2. We've learned:\n\n1. The grammar of graphics approach to building visualisations layer by layer\n2. How to create and interpret histograms, density plots, boxplots, and scatterplots\n3. How to quantify and interpret distribution properties like skewness and kurtosis\n4. How to compare groups using boxplots and faceting\n5. How to examine relationships between variables using scatterplots and trend lines\n6. How to combine multiple plots using the patchwork package\n\nThese skills will be valuable for exploring and presenting data in future labs and assignments.\n\n## Additional Resources\n\n- [R for Data Science - Data Visualisation chapter](https://r4ds.had.co.nz/data-visualisation.html)\n- [ggplot2 documentation](https://ggplot2.tidyverse.org/)\n- [patchwork package documentation](https://patchwork.data-imaginist.com/)\n- [R Graph Gallery](https://www.r-graph-gallery.com/) - Examples of various visualisations in R\n- [Cookbook for R - Graphs](http://www.cookbook-r.com/Graphs/) - Recipes for common visualisation tasks\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}