{
  "hash": "b99b2efb7e863b9fef15604954ed92e7",
  "result": {
    "engine": "knitr",
    "markdown": "# Exploratory Data Analysis EDA\n\n## Numerical Summaries\n\nThe summary descriptive characteristics of a sample of objects, that is, a subset of the population, are called statistics. Sample statistics can have different values, depending on how the sample of the population was chosen. Statistics are denoted by various symbols, but (almost) never by Greek letters e.g. sample mean, $\\bar y$ and sample standard deviation, $s$.\n\n### Measures of Central Tendency\n\nThese statistics are also sometimes referred to as measures of location.\n\n**ARITHMETIC MEAN**\n\nThe most widely used measure of central tendency is the arithmetic mean or average. The population mean, $\\mu$ (“mu”) is the sum of all the values of the variable under study divided by the total number of objects in the population, Each value is algebraically denoted by a $y$ with\na subscript denotation $i$. E.g. a small theoretical population whose objects had values 1, 6, 4, 5, 6, 3, 8, 7 would be denoted:\n\n$$y_1 = 1,\\ y_2 = 6,\\ y_3 = 4,\\ y_4 = 5,\\ y_5 = 6,\\ y_6 = 3,\\ y_7 = 8,\\ y_8 = 7$$\n\n::: {.callout-note}\nSome texts will use $X$ instead of $x$ or $Y$ instead of $y$ as the symbol for a value.\n:::\n\nWe would denote the population size with a capital $N$. In our theoretical population $N = 8$.\n\nThe **population mean**, $\\mu$, would be:\n\n$$\\frac{1+6+4+5+6+3+8+7}{8}=5$$\n\nThe algebraic shorthand formula for a population mean is\n\n$$\\mu = \\frac{1}{N}\\sum_{i=1}^{N} y_i$$\n\nThe Greek letter $\\Sigma$ (“sigma”) indicates summation, the subscript $i = 1$ means to start with the first observation, and the superscript $N$ means to continue until and including the $N$th observation.\n\nFor the example above,\n\n$$\\sum_{i=2}^{5} y_i=y_2+y_3+y_4+y_5=6+4+5+6=21$$\n\nTo reduce the clutter, if the summation sign is not indexed, for example $y_i$, it is implied that the operation of addition begins with the first observation and continues through the last observation in a population, that is,\n\n$$\\sum_{i=1}^{N} y_i = \\sum y_i$$\n\nThe **sample mean** is defined by\n\n$$\\bar y = \\frac{1}{n}\\sum_{i=1}^{n} y_i$$\n\nwhere $n$ is the sample size.\n\nThe symbol $\\bar y$ (read “y bar”) indicates that the observations of a subset of size n from a population have been averaged. $y$ is fundamentally different from $\\mu$ because samples from a population can have different values for their sample mean, that is, they can vary from sample to sample within the population. The population mean, however, is constant for a given population.\n\nAgain consider the small theoretical population $1, 6, 4, 5, 6, 3, 8, 7$. A sample size of 3 may consist of $5, 3, 4$ with $\\bar y =6$ OR it could be $1,3,5$ with $\\bar y = 3$\n\nEach sample mean $\\bar y$ is an unbiased estimate of $m$ but depends on the values included in the sample and sample size for its actual value. We would expect the average of all possible $y$’s to be equal to the population parameter, $\\mu$. This is, in fact, the definition of an unbiased estimator of the population mean.\n\nThe R function is `mean()`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny <- c(1, 6, 4, 5, 6, 3, 8, 7)\nmean(y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5\n```\n\n\n:::\n:::\n\n\n\n\nThe Excel command is `=AVERAGE()`\n\n**MEDIAN**\n\nThe median is the “middle” value of an ordered list of observations. The **population** median $M$ is the $\\left( \\frac{N+1}{2} \\right)th$ sorted value, where $N$ is the population size. Note that this parameter is not a\nGreek letter and is seldom computed in practice. A **sample median** $\\tilde y$ (read “y tilde”) is the statistic used to approximate or estimate the population median. $\\tilde y$ is the $\\left( \\frac{n+1}{2} \\right)th$ sorted value where n is the sample size.\n\nThe R function is `median()`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny <- c(1, 6, 4, 5, 6, 3, 8, 7)\nmedian(y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.5\n```\n\n\n:::\n:::\n\n\n\n\nThe Excel command is `=MEDIAN()`.\n\n**MODE**\n\nThe mode is the most frequently occurring value in a data set.\n\nThere is no direct function for the mode in R, the following code is an example of how it can be calculated.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmode_function <- function(x) {\n  uniqx <- unique(x)\n  uniqx[which.max(tabulate(match(x, uniqx)))]\n}\n\n# Example usage\ny <- c(1, 6, 4, 5, 6, 3, 8, 7)\nmode <- mode_function(y)\nprint(mode)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6\n```\n\n\n:::\n:::\n\n\n\n\nThe Excel command is `=MODE()`.\n\n**OVERVIEW OF MEASURES OF CENTRAL TENDENCY:**\n\n- The mean is a purposeful measure only for a quantitative variable, whether it is continuous (e.g. height) or discrete (e.g. number of nematodes).\n- The median can be calculated whenever a variable can be ranked (including when the variable is quantitative).\n- The mode can be calculated for categorical variables, as well as for quantitative and ranked variables.\n- The sample median expresses less information than the sample mean because it utilizes the ranks and not the actual values of each measurement.\n- The median, however, is resistant to the effects of outliers. Extreme values or outliers in a sample can drastically affect the sample mean, while having little effect on the median.\n\n### Measures of Spread\n\nMeasures of central tendency alone are not sufficient to fully describe a data set. The following figure illustrates 3 distributions that all have the same mean but different levels of dispersion or spread.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\n# Define the data for the three normal distributions\nmean_value <- 0\nstd_dev_A <- 1   # Least spread\nstd_dev_B <- 2\nstd_dev_C <- 3   # Most spread\n\n# Create a data frame for plotting\nx_values <- seq(-10, 10, length.out = 300)\nnormal_data <- data.frame(\n  x = c(x_values, x_values, x_values),\n  y = c(dnorm(x_values, mean_value, std_dev_A), \n        dnorm(x_values, mean_value, std_dev_B), \n        dnorm(x_values, mean_value, std_dev_C)),\n  curve = factor(c(rep(\"A\", length(x_values)), \n                   rep(\"B\", length(x_values)), \n                   rep(\"C\", length(x_values)))\n  )\n)\n\n# Generate the plot\nggplot(normal_data, aes(x = x, y = y, color = curve)) +\n  geom_line() +\n  labs(title = \"Normal Distributions with Different Spreads\",\n       x = \"Value\",\n       y = \"Density\") +\n  scale_color_manual(values = c(\"red\", \"green\", \"blue\"),\n                     labels = c(\"A: Least Spread\", \"B\", \"C: Most Spread\")) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Figure 1.1 A, B & C are distributions with the same mean (zero) but varying standard deviations.](020-exploring_data_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n\nIn graph A, most of the values are concentrated around the mean. It has less dispersion (or spread of values) than the other distributions. Graph C has more dispersion than the others. Its data is more “spread” out.\nA measure of dispersion provides some indication of the amount of variation that the data exhibits.\n\n**RANGE**\n\nThe simplest measure of dispersion or “spread” is the range – the difference between the largest and smallest observations in a group of data.\n\nThe sample range is a crude and biased estimator of the population range as its dependent on the composition and size of the sample you’ve taken. [It’s unlikely that the sample will include the largest and smallest values from the population, so the sample range usually underestimates the population range and is, therefore, a *biased* estimator.]\n\nThe R function is `max(y)-min(y)`\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny <- c(1, 6, 4, 5, 6, 3, 8, 7)\nmax(y)-min(y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7\n```\n\n\n:::\n:::\n\n\n\n\nThe Excel command is `=MAX()-MIN()`\n\n**INTERQUARTILE RANGE**\n\nRather than describe variability in terms of variation around the mean, we more directly quantify the “spread”. Just as the median divides the sample into two, the quartiles divide the sample into four groups:\n\n- 25% of observations $\\le$ lower quartile (Q1) \n- 50% of observations $\\le$ median (Q2) \n- 75% of observations $\\le$ upper quartile (Q3)\n\nThe example data below (the number of days pigs take to reach bacon weight) has been sorted from lowest to highest.\n\n98 100 100 103 105 107 110 113 115 \n\nThe lower quartile Q1 is the $\\left( \\frac{n+1}{4} \\right)th$ sorted value = $\\left( \\frac{9+1}{4} \\right)th = 2.5th$ sorted value.\n\nThis means we need to obtain a *weighted* average of the 2nd and 3rd sorted value: $$0.5 \\times 100 + 0.5 \\times 100 = 100 \\text{ days}$$\n\nThe upper quartile Q3 is the $\\left( \\frac{3(n+1)}{4} \\right)th$ sorted value = $\\left( \\frac{3(9+1)}{4} \\right)th = 7.5th$ sorted value.\n\nThis means we need to obtain a *weighted* average of the 2nd and 3rd sorted value: $$0.5 \\times 110 + 0.5 \\times 113 = 111.5 \\text{ days}$$\n\nThe inter quartile range = Upper Quartile - Lower Quartile\n\n$$IQR = Q3-Q1=111.5-100=11.5 \\text{ days}$$\n\nSo 50% of pigs reach bacon weight within a range of 11.5 days.\n\nThe following is an example of calculations in R - note that we use the type 6 calculation and the default in R is type 7 which we generally use.\n\nFor more information see:\n\n- Hyndman, R.J. and Fan, Y., 1996. Sample quantiles in statistical packages. The American Statistician, 50(4), pp.361-365.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny <- c(98, 100, 100, 103, 105, 107, 110, 113, 115)\n\nquantile(y, 0.75, type = 6) - quantile(y, 0.25, type = 6) ## Type 6\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 75% \n11.5 \n```\n\n\n:::\n\n```{.r .cell-code}\n## Default which we will generally use going forward\nquantile(y, 0.75) - quantile(y, 0.25) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n75% \n 10 \n```\n\n\n:::\n:::\n\n\n\n\n**PERCENTILES**\n\nThe 5th and 95th percentiles cut off 5% of the most extreme values in the distribution of values for the sample. The 1st and 99th percentiles may be similarly defined. As with quartiles, a list of percentiles may be far more informative than the standard deviation for summarizing the spread\nof values about the mean or median, especially when the spread is asymmetrical.\n\n**VARIANCE**\n\nIn general, we have $n$ observations, so the general formula for the sample variance is\n\n$$s^2 = \\frac{1}{n-1}\\sum_{i=1}^{n} (y_i - \\bar{y})^2$$\n\nThe units for the variance are always the units of the original measurement squared. If units of measurement were kg (e.g. body weight), then the variance would have units $kg^2$.\n\n**STANDARD DEVIATION**\n\nTo have a measure of variability with the same units as the original measurement, we take the square root of the variance. This is the standard deviation of the observations (usual symbol is s).\n\nSample standard deviation,\n\n$$s = \\sqrt{\\frac{1}{n-1}\\sum_{i=1}^{n} (y_i - \\bar{y})^2}$$\n**DEGREES OF FREEDOM**\n\nThe value n-1 in the above equations for variance and standard deviation is referred to as the degrees of freedom (df). Ashcroft & Pereira (2003) explain this concept in the following way.\n\n“The degrees of freedom in our analysis is the number of observations that are allowed to vary if our sample characteristic is to estimate precisely the population characteristic. For instance, when we are estimating just one population characteristic like the population variance and out sample size is n, the degrees of freedom is n-1 since control of just one observation (i.e. the rest are free to vary) is all that is required to make our sample variance exactly equal to the population variance.\n\nAs an example, suppose we have a sample of 5 observations $(x_1, x_2, x_3, x_4, x_5; n=5)$ from a population whose mean is 6. Observe in the table below how control of the last observation can make our sample mean exactly equal to the population mean of 6 when the first 4 observations are free to change their values.\n\n| x1 | x2 | x3 | x4 | (Make x5) | Sample mean\n|:---|:---|:---|:---|:----------|:-----------\n| 2  | 4  | 7  | 8\t| (9)       | 6\n| 4  | 6  | 5  | 7\t| (8)       | 6\n| 3  | 7  | 4  | 9\t| (7)       | 6\n\n\nHere we see that a group of 5 observations being used to estimate a single population characteristic has 4 degrees of freedom. In general, when k population characteristics are being estimated from n observations, the degrees of freedom of the analysis is n-k.”\n\n**COEFFICIENT OF VARIATION**\n\nThe coefficient of variation (CV) is used is used to aide in comparing the variability of two samples that have widely differing means. It is usually expressed as a percentage, and has no units.\n\n$$CV = \\frac{s}{\\bar{y}} \\times 100\\%$$\n\n## Tabular Summaries\n\n### Tables of means\n\nTables are a way of organizing the data collected or providing a summary presentation of the data. The two most common types of tabular summaries you will encounter are tables of means and frequency tables.\n\nAn example of a table of means is the following table that shows the mean number of sedge plants, Carex flacca, found in 800 sample quadrats in an ecological study of grasses. Each quadrat was randomly assigned to one of four treatments: control, low, medium, and high. The table shows the mean number of sedge plants found in each treatment. We will simulate the data for this example.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(kableExtra)\n\nset.seed(123) # For reproducibility\n\n# Simulate data\nquadrats <- data.frame(\n  Treatment = factor(rep(c(\"Control\", \"Low\", \"Medium\", \"High\"), each = 200)),\n  SedgePlants = c(\n    rpois(200, lambda = 5),  # Assuming a Poisson distribution for count data \n    rpois(200, lambda = 10),\n    rpois(200, lambda = 15),\n    rpois(200, lambda = 20)\n  )\n)\n\nquadrats <- quadrats %>%\n  group_by(Treatment) %>%\n  summarise(MeanSedgePlants = mean(SedgePlants))\nkable(quadrats)\n```\n\n::: {.cell-output-display}\n\n\n|Treatment | MeanSedgePlants|\n|:---------|---------------:|\n|Control   |           5.060|\n|High      |          20.050|\n|Low       |           9.955|\n|Medium    |          14.860|\n\n\n:::\n:::\n\n\n\n\n### Frequency Tables\n\nAn example of a tabular summary is the following table that shows the number of sedge plants, Carex flacca, found in 800 sample quadrats in an ecological study of grasses. Each quadra\n\nSedge plant data sourced from Glover & Mitchell (2002)\n\n| Plants/quadrat $(y_i)$ |\tFrequency $(f_i)$\n|:-----------------------|:-------------------\n| 0\t                     | 268\n| 1\t                     | 316\n| 2\t                     | 135\n| 3\t                     | 61\n| 4\t                     | 15\n| 5\t                     | 3\n| 6\t                     | 1\n| 7\t                     | 1\n\nThis table can be further organized into a **relative frequency** $(f_i/n \\times 100)$ table by expressing each row as a percentage of the total observation or into a **cumulative frequency** distribution by accumulating all observations up to and including each row i.e. $\\Sigma^r_{i=1}f_i$ where $r$ is the row number. The cumulative frequency distribution could be further manipulated into a **relative cumulative frequency** distribution by expressing each row of the cumulative frequency distributions as a percentage of the total i.e.  $\\Sigma^r_{i=1}f_i/n \\times 100$\n\n## Graphical Summaries\n\n### Bar Graphs and Histograms\n\nFrequency tabulations can be represented as a graph of frequency (raw or percentage) against the measurement variable. Discrete data are sometimes expressed as a bar graph where bars are spaced equidistantly along the horizontal axis. Figure 1.2 is a relative frequency histogram\n(also known as a percentage frequency histogram) of the sedge plant data. The data represents data from sedge plant counts in 800 1m x 1m quadrats Ideally this data set (since it is discrete) would be plotted as a bar graph.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nsedge <- read_csv(\"data/Sedge.csv\", show_col_types = FALSE)\n\nggplot(sedge, aes(x = Plants)) +\n  geom_histogram(aes(y = after_stat(count)/sum(after_stat(count)) * 100), bins = 8) +\n  ylab(\"Percentage\") +\n  xlab(\"Number of plants per quadrat\")\n```\n\n::: {.cell-output-display}\n![Figure 1.2 Relative frequency histogram of sedge plant data.](020-exploring_data_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n\nContinuous measurements are free to take any whole or fractional number within their range e.g. plant height, soil pH, concentration of nitrates in a water sample. Histograms (with bars touching each other) are the norm for continuous data.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbentgrass <- read_csv(\"data/Bentgrass.csv\", show_col_types = FALSE)\n\nggplot(bentgrass, aes(x = Root_length_mm)) +\n  geom_histogram(bins = 20) +\n  xlab(\"Root length (mm)\")\n```\n\n::: {.cell-output-display}\n![Figure 1.3 Frequency histogram of creeping bentgrass data.](020-exploring_data_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n\nA histogram can give nearly complete information about the distribution of data. For example, from Figure 1.3 above (that shows a fairly symmetric distribution) we can estimate that the mean ≈ 95 mm (the centre of the data) and standard deviation ≈ 15 mm (since for symmetric distributions approximately 95% of data lies within 2 standard deviations either side of the mean i.e. a total of 4 standard deviations across 95% of the data values).\n\nA histogram needs a relatively large sample size for it to be informative (i.e. 30 or more data values).\n\n### Boxplots\n\nBoxplots show the shape of the distribution of data very clearly and are also helpful in identifying any outlying (or extreme) values.\n\nExample 1 Creeping bentgrass turf was laid in an experiment to assess root growth. Eighty (80) “plugs” were randomly sampled 4 weeks after laying. Root growth was measured by averaging the length (mm) of the ten longest roots in each plug.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(bentgrass, aes(x = Root_length_mm)) +\n  geom_boxplot() +\n  xlab(\"Root length (mm)\")\n```\n\n::: {.cell-output-display}\n![](020-exploring_data_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n\n\nNotes on boxplots:\n\n- 50% of the data are contained within the box (inter quartile range).\n- Whiskers are extended to a maximum of 1.5 x IQR \n- Any data values beyond these maximum whisker lengths are plotted individually, usually by an asterisk or dot $\\Rightarrow$ these may be **outliers** and distort the results of any further analysis\n- A boxplot gives useful summary of the shape of the data distribution e.g. Is it symmetric or skewed? Are there any outliers?\n- Boxplots do not need as many data values (as some other graphs such as histograms and dot plots) for them to be informative.\n\n**GUIDELINES FOR MAKING A BOXPLOT**\n\nWe will use the gravimetric water content of soil (%) from Method A in the irrigation data set to illustrate how a boxplot is constructed. In this example we have n = 10 observations. We can use the R function, `summary()` to calculate some of the important values in a boxplot such as Q1, Q2, and Median.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsoil_water <- data.frame(water_content = c(7.5, 9.0, 9.3, 10.4, 10.4, 10.6, 10.7, 11.6, 12.1, 12.8))\n\nsummary(soil_water$water_content)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  7.500   9.575  10.500  10.440  11.375  12.800 \n```\n\n\n:::\n:::\n\n\n\n\n**Step 1:** Determining the Box: \n\n- The quartiles (Q1: 1st Qu. & Q3: 3rd Qu.) then become the basis for the “box” \n- The median is shown as a vertical line through the box.\n\n**Step 2:** Determining (potential) outliers\n\n- Calculate IQR = Inter-quartile range = 11.375 - 9.575 = 1.8\n- Calculate Q1 - 1.5 x IQR = 9.225 - 1.5 x 1.8 = 6.875 Since there are no observations smaller than 6.875, there are no low-valued outliers.\n- Calculate Q3 + 1.5 x IQR = 11.375 + 1.5 x 1.8 = 14.075 Since there are no observations greater than 14.075, there are no high-valued outliers.\n- If any values were flagged to be (potential) outliers, they are plotted as individual points on the boxplot, usually as a \"*\" or $\\bullet$.\n\n**Step 3:** Determining the “whisker” lengths\n\n- Extend the whisker from the lower end of the box (Q1) to the smallest value that is not an outlier, i.e. to the smallest value greater then Q1 - 1.5 x IQR. That is, the whisker here will be extended down to the minimum value which is 7.5.\n- Extend the whisker from the upper end of the box (Q3) to the largest value that is not an outlier, i.e. to the greatest value smaller then Q3 + 1.5 x IQR. That is, the whisker here will be extended up to 12.8.\n\nUsing these values, the following boxplot is obtained:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(soil_water, aes(x = water_content)) +\n  geom_boxplot() +\n  xlab(\"gravimetric water content of soil (%)\")\n```\n\n::: {.cell-output-display}\n![](020-exploring_data_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\n\n### Scatterplots\n\nScatter plots are used to represent graphically the relationship between two variables. The extent and nature of the relationship between two (or more) variables is quantified through tools such as correlation and regression. This will be covered in later chapters.\n\n## Shapes of Distributions\n\n### Symmetric\n\nThis is a distribution such that the left hand side of the frequency polygon is a mirror image of the right hand side. For symmetrical distributions, the mean, median and mode all have the same value. Substantial differences in these three statistics could provide valuable information about the data set (as we’ll see in the sections on positively and negatively skewed distributions). Some examples of symmetric distributions appear below.\n\n![Figure 1.4 Four examples of symmetric distributions.](images/symmetric.png)\n\nExample: Creeping bentgrass: root growth (mm)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(bentgrass)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Root_length_mm  \n Min.   : 65.00  \n 1st Qu.: 86.75  \n Median : 93.00  \n Mean   : 93.86  \n 3rd Qu.:102.00  \n Max.   :135.00  \n```\n\n\n:::\n:::\n\n\n\n\nNote that the mean and the median are similar (93.9, and 93.0 mm respectively). This is indicative of symmetric data.\nThe boxplot and histogram below show that the data is symmetric about the mean. You will notice from the boxplot that there is one high value outlier indicated by the \"x\" at the right hand side of the graph. The \"4\" indicates that this is the 4th observation in the data set i.e. the value 135 mm.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(patchwork)\np1 <- ggplot(bentgrass, aes(x = Root_length_mm)) +\n  geom_boxplot() +\n  xlab(\"Root length (mm)\")\np2 <- ggplot(bentgrass, aes(x = Root_length_mm)) +\n  geom_histogram(bins = 20) +\n  xlab(\"Root length (mm)\")\np1+p2\n```\n\n::: {.cell-output-display}\n![Figure 1.5 Boxplot (left) and histogram (right) of the creeping bentgrass data show symmetry.](020-exploring_data_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n\n### Positively Skewed\n\nFor right-skewed distributions we find that the mode (if one exists) is always less than the median and the median is always less than the mean.\nExample: As part of an evaluation of a clean-up of a contaminated site, 100 soil samples were taken randomly across an area and the level of 1,2,3,4 Tetrachlorobenzene was recorded in parts per billion (TcCB, ppb). \n\nThe following descriptive analysis was undertaken.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntccb <- read_csv(\"data/TcCB.csv\", show_col_types = FALSE)\n\nsummary(tccb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    TcCB_ppb     \n Min.   : 0.010  \n 1st Qu.: 0.235  \n Median : 0.570  \n Mean   : 1.412  \n 3rd Qu.: 1.292  \n Max.   :26.600  \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(tccb, aes(x = TcCB_ppb)) +\n  geom_boxplot() +\n  xlab(\"TcCB concentration (ppb)\")\np2 <- ggplot(tccb, aes(x = TcCB_ppb)) +\n  geom_histogram(bins = 20) +\n  xlab(\"TcCB concentration (ppb)\")\np1+p2\n```\n\n::: {.cell-output-display}\n![Figure 1.6 Boxplot (left) and histogram (right) of the TcCB data showing positive skewness.](020-exploring_data_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\n\nThe distribution is highly positively skewed (right skewed): there are extreme outliers at high levels. This is also demonstrated by the mean (1.412 ppb) being substantially greater than the median (0.570 ppb).\n\n### Negatively Skewed\n\nFor left-skewed distributions we find that the mode is greater than the median and the median is greater than the mean.\n\nExample:\n- The age of onset of osteoarthritis was recorded in 13 dogs. \n- The majority of the values cluster around the 10-13 age range, which represents the more common onset age for the chronic condition in older dogs.\n- There are also some lower values representing the less common earlier onset of the condition.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\narthritis <- read_csv(\"data/Arthritis.csv\", show_col_types = FALSE)\n\nsummary(arthritis)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   AgeAtOnset    \n Min.   : 3.800  \n 1st Qu.: 7.225  \n Median :11.150  \n Mean   : 9.714  \n 3rd Qu.:12.000  \n Max.   :13.200  \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(arthritis, aes(x = AgeAtOnset)) +\n  geom_boxplot() +\n  xlab(\"Age at onset (years)\")\np2 <- ggplot(arthritis, aes(x = AgeAtOnset)) +\n  geom_histogram(bins = 5) +\n  xlab(\"Age at onset (years)\")\np1+p2\n```\n\n::: {.cell-output-display}\n![Figure 1.7 Boxplot (left) and histogram (right) of arthritis data showing negative skewness.](020-exploring_data_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n\n\nThe distribution is negatively skewed (left skewed): there are some outliers at low levels. This is also demonstrated by the mean (9.7 years) being marginally less than the median (11.1 years).\n\n### Statistics of Shape\n\nThere are two statistics useful for describing shape.\n\n**SKEWNESS**\n\nSkewness is another name for asymmetry which means that one tail of the frequency distribution is drawn out more than the other. A skewness of zero implies a symmetrically shaped histogram, a negative value implies skewness to the left and a positive value implies skewness to the right.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(moments)\nskewness(bentgrass)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRoot_length_mm \n    0.08475045 \n```\n\n\n:::\n\n```{.r .cell-code}\nskewness(tccb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTcCB_ppb \n5.998866 \n```\n\n\n:::\n\n```{.r .cell-code}\nskewness(arthritis)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAgeAtOnset \n-0.8257301 \n```\n\n\n:::\n:::\n\n\n\n\n**KURTOSIS**\n\nKurtosis is a measure of how “peaked” (leptokurtic) a frequency distribution is or how “flattened” (platykurtic) it is. A negative value indicates platykurtosis (or flatness), and a positive value indicates leptokurtosis (peakedness).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkurtosis(bentgrass)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRoot_length_mm \n      3.354701 \n```\n\n\n:::\n\n```{.r .cell-code}\nkurtosis(tccb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTcCB_ppb \n46.11769 \n```\n\n\n:::\n\n```{.r .cell-code}\nkurtosis(arthritis)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAgeAtOnset \n  2.030982 \n```\n\n\n:::\n:::\n\n\n\n\n**BIMODAL**\n\nNote: Bimodal distributions expected indicate a mixture of samples from two populations (e.g. weights of male and females). While the mode is not often used in biological research, reporting the number of modes, if more than one, can be informative.\n\n## Normality versus Non-Normality (in the Descriptive Statistics Context)\n\n### Normality\n\nMost natural groups of objects show variation. Humans differ in height, even if of the same sex, race and age. In many instances, measurements of similar objects vary about their mean according to a well-defined function, the normal or Gaussian distribution function.\n\nThe normal distribution has the following characteristics:\n\n-\tIt is symmetric about its mean, median and mode. Hence a normal distribution has a skewness of zero.\n-\tIt is bell-shaped, with a kurtosis of zero (recall kurtosis is “flatness”).\n-\tIt is a continuous curve defined for values from minus infinity to plus infinity.\n-\tIt is completely defined by its mean and standard deviation. That is, if you know the mean and standard deviation of the normal curve, you can calculate its exact equation. \n  - PDF for normal distribution:  $f(x) = \\frac{1}{\\sqrt{2\\pi\\sigma^2}}e^{-\\frac{(x-\\mu)^2}{2\\sigma^2}}$\n-\t95% of observations fall in the range defined by the mean plus or minus 1.96 standard deviations and 99% fall in the range defined by the mean plus or minus 2.58 standard deviations.\n\n**Summary statistics** for a sample drawn from a normally distributed population **would usually** include the range of values encountered, the arithmetic **mean**, the **standard deviation** and the **size of the sample** from which these statistics were calculated. All other information, including the frequency tabulation, the mode, median, percentiles, sample skewness and kurtosis would be superfluous.\n\nWe will look at the normal distribution in detail later in this section.\n\n### Non-Normality\n\nFor data that do not conform to the theoretical normal distribution, the situation is more complex. No longer will the mean and standard deviation suffice in order to reconstruct the frequency distribution of the raw data. No longer would we expect only 5% of values to lie outside the mean plus or minus 1.96 standard deviations. **A more detailed description of the characteristics of non-normal data is required**.\n\nSubstantial differences between the model, median and arithmetic mean are apparent when a skewed distribution is considered. Clearly the three averages can have distinctly different values. Which is the most appropriate average? The mean is markedly affected by outlying observations whereas the median and mode are not.\n\nThe difference between the mean and median has important practical consequences for analysis of data that contains aberrant outlying values (perhaps because of errors at the time of measurement or during transcription in preparing the data). Such errors, if they go unnoticed, can seriously affect an analysis.\n\nMost modern statistical packages perform various tests to determine if your data are likely to have been drawn from a normally distributed population. We’ll look at these later.\n \n\n",
    "supporting": [
      "020-exploring_data_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}