---
title: "ENVX1002 Handbook"
date: today
date-format: YYYY

---

**Welcome to the ENVX1002 lab handbook.** This handbook is designed to be a useful companion to the lectures, labs and assessments.

## Quick links

- [ENVX1002 Unit page](https://www.sydney.edu.au/units/ENVX1002) -- check assessment weights, due dates, and other important information
- [Canvas](https://canvas.sydney.edu.au) -- the main hub
- [Ed discussion forum](https://edstem.org/au/dashboard) -- ask questions, share resources, and get help

## How to use this handbook

Read this handbook before, or *after* each lecture to better understand certain concepts. Computer lab exercises are also included, which you can use to prepare for the lab sessions.

To begin, we strongly suggest that you read our [introduction](/001-intro.qmd) chapter (which will align with Week 1 Lectures) to get an overview of why ENVX1002 is important for your degree and includes some introductory statistical concepts.

::: {.callout-note collapse="true"}
## Acknowledgements

We would like to acknowledge the work of previous generations of teaching staff who created the bulk of the teaching material within this manual. In particular, the work of:

- Assoc. Prof. Mick O’Neill
- Dr. Kathryn Aufflick
- Assoc. Prof. Peter Thomson
- Prof. Thomas Bishop
:::

::: {.callout-tip collapse="true"}
## License
This handbook is licensed under a [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-nc-sa/4.0/).
:::


When you are ready, check the sidebar to get started.