{
  "hash": "03f4d7058533a4ca600ec6699a884f06",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Lab 05 -- Hypothesis testing\nembed-resources: true\nresources:\n  - data/ENVX1002_Data5.xlsx\n---\n\n\n\n\n\n\n\n\n## Welcome\n\n:::{.callout-tip}\n## Learning outcomes\n\n- Learn to use R to calculate a 1-sample t-test\n- Apply the steps for hypothesis testing from lectures\n- Learn how to interpret statistical output  \n:::\n\n# Before you begin\n\nYou can download the data\n\n1) From module 5 in Canvas\n2) [ENVX1002_Data5.xlsx](data/ENVX1002_Data5.xlsx) if you are viewing the html file from Github <https://Github.com/envx-resources>\n\n\n## Create a new project  \n\nReminder (skip to step 2 if you are going to use the directory you created in your tutorial)\n\n**Step 1:** Create a new project file for the practical put in your ENVX1002 Folder. *File > New Project > New Directory > New Project*.  \n\n**Step 2:** Download the data files from canvas or using above link and copy into your project directory.  \n\nI recommend that you make a data folder in your project directory to keep things tidy! If you make a data folder in your project directory you will need to indicate this path before the file name. \n\n**Step 3:** Open a new Quarto file.  \n\ni.e. *File > New File > Quarto Document* and save it immediately i.e. File > Save.\n\n## Problems with your personal computer and R\n\nNOTE: If you are having problems with R on your personal computer that cannot easily be solved by a demonstrator, please use the Lab PCs. \n\n## Installing packages\n\n**Remember** All of the functions and data sets in R are organised into packages. There are the standard (or base) packages which are part of the source code - the functions and data sets that make up these packages are automatically available when R is opened. There are also many contributed packages. These have been written by many different authors, often to implement methods that are not available in the base packages. If you are unable to find a method in the base packages, you might be able to find it in a contributed package. The Comprehensive R Archive Network (CRAN) site [(http://cran.r-project.org/)](http://cran.r-project.org/) is where many contributed packages can be downloaded. Click on packages on the left hand side. We will download two packages in this class using the ```install.packages``` command and we then load the package into R using the library command. \n\nAlternatively, in RStudio click on the *Packages tab > Install > type in package name > click install*.\n\n\n# Exercise 1: 1-sample t-test Milk Yield - Walk through\n\nThis exercise will walk you through how to test a hypothesis, check assumptions and eventually draw a conclusion on your initial hypothesis. 100 cows have their milk yield measured. Suppose we wish to test whether these milk yields (units unknown) differ significantly from the economic threshold of 11 units. (The units may possibly be litres of milk produced on a particular day). \n\n:::{.callout-tip}\n## Fact\nThe average Australian drinks about 100 litres of milk per year. The average cow produces between 12 and 30 litres of milk per day. \n:::\n\nThe data is in the `Milk` sheet found in the `ENVX1002_Data5.xlsx` file. You will follow the steps as outlined in the lectures:  \n\n1. Choose level of significance (α)\n2. Write null and alternate hypotheses\n3. Check assumptions (normal)\n4. Calculate test statistic\n5. Obtain P-value or critical value\n6. Make statistical conclusion\n7. Write a scientific (biological) conclusion\n\nRemember you can remember the above using **HATPC**\n\nLets go:  \n  \n## 1. Normally you choose *0.05* as a level of significance: \n\nThis value is generally accepted in the scientific community and is also linked to type 2 errors where choosing a lower significance increases the likelihood of a type 2 error occurring.  \n\n## 2. Write null and alternative hypotheses:\n\n----\n\n> **_Question:_** Write down the null hypothesis and alternative hypotheses:    \n> H~0~:  < Type your answer here >    \n> H~1~:  < Type your answer here >    \n\n----\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n----\n\n> **_Question:_** Write down the null hypothesis and alternative hypotheses:    \n> H~0~:  $\\mu_{yield}$ = 11 units   \n> H~1~:  $\\mu_{yield}$ $\\neq$ 11 units     \n\n----\n\n:::\n\n\n## 3. Check assumptions (normality):  \n\n\n### a. load data:\n    \n\n*Make sure you set your working directory first*\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Type your R code here\n```\n:::\n\n\n\n\n\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nmilk <- read_excel(\"data/ENVX1002_Data5.xlsx\", sheet = \"Milk\")\n```\n:::\n\n\n\n\n\n\n:::\n\nIt is always good practice to look at the data first to make sure you have the correct data, it loaded in correctly and know what the names of the columns are. This can be done by typing the name of the data ```Milk``` or for large datasets, use ```str()``` to show the first 6 lines:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Type your R code here\n```\n:::\n\n\n\n\n\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(milk)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [100 × 1] (S3: tbl_df/tbl/data.frame)\n $ Yield: num [1:100] 18.5 15.9 13.1 15.1 5.7 9.4 15.3 17.6 18.4 22 ...\n```\n\n\n:::\n:::\n\n\n\n\n\n\n:::\n\n### b. Tests for normality:\n\nqqplots:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Type your R code here\n```\n:::\n\n\n\n\n\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Load library\nlibrary(ggplot2)\n\nggplot(milk, aes(sample = Yield)) +\n  stat_qq() +\n  stat_qq_line()\n```\n\n::: {.cell-output-display}\n![](Lab05_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n:::\n\nHistogram and boxplots:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Type your R code here\n```\n:::\n\n\n\n\n\n\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Histogram\nggplot(milk, aes(x = Yield)) +\n  geom_histogram(binwidth = 1, fill = \"lightblue\", color = \"black\") +\n  labs(title = \"Histogram of Milk Yield\", x = \"Yield\", y = \"Frequency\")\n```\n\n::: {.cell-output-display}\n![](Lab05_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#Boxplot\nggplot(milk, aes(x = Yield)) +\n  geom_boxplot(fill = \"lightblue\", color = \"black\")\n```\n\n::: {.cell-output-display}\n![](Lab05_files/figure-html/unnamed-chunk-8-2.png){width=672}\n:::\n:::\n\n\n\n\n\n\n:::\n\n----\n\n>**_Question:_** Do the plots indicate the data are normally distributed?  \n>**_Answer:_**  < Type your answer here >\n\n----\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n----\n\n>**_Question:_** Do the plots indicate the data are normally distributed?  \n>**_Answer:_**  yes - think about why?\n\n---\n\n:::\n\nShapiro-Wilk test of normality:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Type your R code here\n```\n:::\n\n\n\n\n\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(milk$Yield)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  milk$Yield\nW = 0.98967, p-value = 0.6379\n```\n\n\n:::\n:::\n\n\n\n\n\n\n:::\n\n----\n\n>**_Question:_** Does the Shapiro-Wilk test indicate the data are normally distributed? Explain your answer.  \n>**_Answer:_**  < Type your answer here >\n\n----\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n----\n\n>**_Question:_** Does the Shapiro-Wilk test indicate the data are normally distributed? Explain your answer.  \n>**_Answer:_**  yes. p-value > 0.05.\n\n----\n\n:::\n\n## 4. Calculate the test statistic\n\n\nIn R we achieve this via the command ```t.test(milk$Yield, mu = …)```\nThe R output first gives us the calculated t value, the degrees of freedom, and then the p-value, it then provides the 95% CI and the mean of the sample. Were `mu = …` is written enter in the hypothesised mean.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# write your R code here\n```\n:::\n\n\n\n\n\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(milk$Yield, mu = 11)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  milk$Yield\nt = 4.9291, df = 99, p-value = 3.323e-06\nalternative hypothesis: true mean is not equal to 11\n95 percent confidence interval:\n 12.53485 14.60315\nsample estimates:\nmean of x \n   13.569 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n:::\n\n### 5. Obtain P-value or critical value\n\n----\n\n>**_Question:_** Does the hypothesised economic threshold lie within the confidence intervals?  \n>**_Answer:_**  < Type your answer here >\n\n----\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n----\n\n>**_Question:_** Does the hypothesised economic threshold lie within the confidence intervals?  \n>**_Answer:_**  No\n\n----\n\n:::\n\n### 6. Make statistical conclusion\n\n----\n\n>**_Question:_**: Based on the P-value, do we accept or reject the null hypothesis?  \n>**_Answer:_**  < Type your answer here >\n\n----\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n----\n\n>**_Question:_**: Based on the P-value, do we accept or reject the null hypothesis?  \n>**_Answer:_**  Reject the null hypothesis\n\n----\n\n:::\n\n### 7. Write a scientific (biological) conclusion\n\n----\n\n>**_Question:_**: Now write a scientific (biological) conclusion based on the outcome in 6.  \n>**_Answer:_**  < Type your answer here >\n\n----\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n----\n\n>**_Question:_**: Now write a scientific (biological) conclusion based on the outcome in 6.  \n>**_Answer:_**  The milk yields differ significantly from the economic threshold of 11 units. In fact, the cows tested yield an average of 13.6 units (95% CI: 12.5, 14.6), which is significantly higher than the economic threshold of 11 units.\n\n----\n\n:::\n\n# Exercise 2: Stinging trees (individual or in pairs)\n\nData file: Stinging.csv  \n\nA forest ecologist, studying regeneration of rainforest communities in gaps caused by large trees falling during storms, read that stinging tree, **Dendrocnide excelsa**, seedlings will grow 1.5m/year in direct sunlight such as gaps. In the gaps in her study plot, she identified 9 specimens of this species and measure them in 1998 and again 1 year later. \n\nDoes her data support the published contention that seedlings of this species will average 1.5m of growth per year in direct sunlight? Also, calculate a 95% CI for the true mean. Analyse the data in R. Due to the small sample size we have to assume the data is normal.\n\n:::{.callout-tip}\n## Fact\nIt was found that researchers wearing welding gloves and a full body suit were still stung by the tree. The sting is extremely painful and can last for months. The pain is caused by a neurotoxin that is injected into the skin. The tree is found in the rainforests of north-eastern Australia.\n:::\n\nWork through the steps below individually or in pairs. Add more code chunks if required (click insert -> R on above toolbar)  \n\n----\n\n>1. Choose level of significance (α)  \n> Answer:  \n\n----\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n----\n\n>1. Choose level of significance (α)  \n> Answer:  0.05 is generally accepted in the scientific community.\n\n----\n\n:::\n\n----\n\n>2. Write null and alternate hypotheses  \n> H~0~:      \n> H~1~:   \n\n----\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n----\n\n>2. Write null and alternate hypotheses  \n> H~0~: $\\mu_{growth}$ = 1.5m/year     \n> H~1~: $\\mu_{growth}$ $\\neq$ 1.5m/year \n\n----\n\n:::\n\n>3. Check assumptions (normal)  \n\nRead in the data:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nsting <- read_excel(\"data/ENVX1002_Data5.xlsx\", sheet = \"Stinging\")\nsting\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 1\n  Stinging\n     <dbl>\n1      1.9\n2      2.5\n3      1.6\n4      2  \n5      1.5\n6      2.7\n7      1.9\n8      1  \n9      2  \n```\n\n\n:::\n:::\n\n\n\n\n\n\nPlot your data:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Type your R code here\n```\n:::\n\n\n\n\n\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#qq plot\nggplot(sting, aes(sample = Stinging)) +\n  stat_qq() +\n  stat_qq_line()\n```\n\n::: {.cell-output-display}\n![](Lab05_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#histogram\nggplot(sting, aes(x = Stinging)) +\n  geom_histogram(binwidth = 1, fill = \"lightgreen\", color = \"black\") +\n  labs(title = \"Histogram of Stinging Tree Growth\", x = \"Growth (m)\", y = \"Frequency\")\n```\n\n::: {.cell-output-display}\n![](Lab05_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Boxplot\nggplot(sting, aes(x = Stinging)) +\n  geom_boxplot(fill = \"lightgreen\", color = \"black\") +\n  labs(title = \"Boxplot of Stinging Tree Growth\", x = \"Growth (m)\", y = \"Frequency\")\n```\n\n::: {.cell-output-display}\n![](Lab05_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n:::\n\n\nNormality tests:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Type your R code here\n```\n:::\n\n\n\n\n\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(sting$Stinging)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  sting$Stinging\nW = 0.96096, p-value = 0.8083\n```\n\n\n:::\n:::\n\n\n\n\n\n\n:::\n\n----\n\n>**_Question:_** Are data are normally distributed? Explain your answer.  \n>**_Answer:_**  < Type your answer here > \n\n----\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n----\n\n>**_Question:_** Are data are normally distributed? Explain your answer.  \n>**_Answer:_**  Yes. Both the plots and Shapiro-Wilk test suggest the data is normal (p-value > 0.05).\n\n----\n\n:::\n\n> 4. Calculate test statistic and  \n> 5. Obtain P-value or critical value  \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Type your R code here\n```\n:::\n\n\n\n\n\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(sting$Stinging, mu = 1.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  sting$Stinging\nt = 2.3534, df = 8, p-value = 0.04643\nalternative hypothesis: true mean is not equal to 1.5\n95 percent confidence interval:\n 1.508055 2.291945\nsample estimates:\nmean of x \n      1.9 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n:::\n\n----\n\n> 6. Make statistical conclusion  \n> Answer:\n\n----\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n----\n\n> 6. Make statistical conclusion  \n> Answer: P < 0.05 so we reject the null hypothesis $\\mu_{growth}$ = 1.5m/year   \n\n----\n\n:::\n\n----\n\n> 7. Write a scientific (biological) conclusion    \n> Answer:\n\n----\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n----\n\n> 7. Write a scientific (biological) conclusion    \n> Answer: The growth rate of the stinging tree, *Dendrocnide excelsa* is not equal to 1.5m/year. The mean growth rate is 1.9 m/year (95% CI: 1.51, 2.29), so the growth rate is faster than the previous study.\n\n----\n\n:::\n\n### Check you answers with teaching staff\n\n\n## Thanks!\n\n# Bonus take home exercices\n\nFor each of these exercises, follow the steps outlined in the lectures (and this lab!) to test your hypotheses:\n\n1. Choose level of significance (α)\n2. Write null and alternate hypotheses\n3. Check assumptions (normal)\n4. Calculate test statistic\n5. Obtain P-value or critical value\n6. Make statistical conclusion\n7. Write a scientific (biological) conclusion\n\n## Exercise 1: Carrots\n\nA farmer is growing carrots for a restaurant. The restaraunt wants their carrots to be 10 cm long, so the farmer wants to check if the carrots in their field differ significantly from the needed length.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Read in data\n\ncarrots <- c(7, 7, 13, 5, 13, 10, 11, 12, 10,  9)\n```\n:::\n\n\n\n\n\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n----\n1. Choose level of significance (α)\n> Answer:  0.05 is generally accepted in the scientific community.\n\n2. Write null and alternate hypotheses\n\n> H~0~: $\\mu_{carrot}$ = 10cm     \n> H~1~: $\\mu_{carrot}$ $\\neq$ 10 cm \n\n3. Check assumptions (normal)\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#boxplot\nboxplot(carrots)\n```\n\n::: {.cell-output-display}\n![](Lab05_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#histogram\nhist(carrots)\n```\n\n::: {.cell-output-display}\n![](Lab05_files/figure-html/unnamed-chunk-23-2.png){width=672}\n:::\n\n```{.r .cell-code}\n#shapiro test\n\nshapiro.test(carrots)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  carrots\nW = 0.93961, p-value = 0.5486\n```\n\n\n:::\n:::\n\n\n\n\n\n> The data are normally distributed\n\n4. Calculate test statistic and\n5. Obtain P-value or critical value\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#t test\nt.test(carrots, mu = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  carrots\nt = -0.35006, df = 9, p-value = 0.7343\nalternative hypothesis: true mean is not equal to 10\n95 percent confidence interval:\n  7.761337 11.638663\nsample estimates:\nmean of x \n      9.7 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n6. Make statistical conclusion\n\n> p > 0.05, so we retain the. null hypothesis\n\n7. Write a scientific (biological) conclusion\n\n> The carrot length is not equal to 10 cm. The farmer's carrots have a mean of 9.7 cm, so they are smaller than the needed length\n\n----\n:::\n\n## Exercise 2: Penguins\n\nRey has just landed on earth and notived that penguins look really similar to porgs. Using weight as the point of comparison, she wants to know if two different penguin species weigh the same as her pet Porg Stevie, who weighs  4000g.\n\nWe will be using the Palmer penguin dataset to test if chinstrap and gentoo penguins weigh the same as Stevie.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages(\"palmerpenguins\")\nlibrary(palmerpenguins)\n```\n:::\n\n\n\n\n\n\n### 2.1 Chinstrap\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchinstrap <-  penguins%>%\n  filter(species == \"Chinstrap\")%>%\n  na.omit()\n```\n:::\n\n\n\n\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n----\n1. Choose level of significance (α)\n> Answer:  0.05 is generally accepted in the scientific community.\n\n2. Write null and alternate hypotheses\n\n> H~0~: $\\mu_{chinstrap}$ = 4000g     \n> H~1~: $\\mu_{chinstrap}$ $\\neq$ 4000g \n\n3. Check assumptions (normal)\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Load library\nlibrary(tidyverse)\n#qqplot\nggplot(chinstrap, aes(sample = body_mass_g))+\n  geom_qq()+\n  geom_qq_line()\n```\n\n::: {.cell-output-display}\n![](Lab05_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#boxplot\nggplot(chinstrap, aes(x = body_mass_g))+\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](Lab05_files/figure-html/unnamed-chunk-27-2.png){width=672}\n:::\n\n```{.r .cell-code}\n#histogram\nggplot(chinstrap, aes(x = body_mass_g))+\n  geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Lab05_files/figure-html/unnamed-chunk-27-3.png){width=672}\n:::\n\n```{.r .cell-code}\n#shapiro test\nshapiro.test(chinstrap$body_mass_g)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  chinstrap$body_mass_g\nW = 0.98449, p-value = 0.5605\n```\n\n\n:::\n:::\n\n\n\n\n\n> The data are normally distributed\n\n4. Calculate test statistic and\n5. Obtain P-value or critical value\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#t test\nt.test(chinstrap$body_mass_g, mu = 4000)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  chinstrap$body_mass_g\nt = -5.7268, df = 67, p-value = 2.631e-07\nalternative hypothesis: true mean is not equal to 4000\n95 percent confidence interval:\n 3640.059 3826.117\nsample estimates:\nmean of x \n 3733.088 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n6. Make statistical conclusion\n\n> p < 0.05, so we reject null hypothesis\n\n7. Write a scientific (biological) conclusion\n\n> Chinstrap penguins do not weigh the same as Stevie. On average, chinstrap penguins weigh 3733.088g, so they are lighter. \n\n----\n:::\n\n### 2.2 Gentoo\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngentoo <-penguins%>%\n  filter(species == \"Gentoo\")%>%\n  na.omit() \n```\n:::\n\n\n\n\n\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n----\n1. Choose level of significance (α)\n> Answer:  0.05 is generally accepted in the scientific community.\n\n2. Write null and alternate hypotheses\n\n> H~0~: $\\mu_{gentoo}$ = 4000g     \n> H~1~: $\\mu_{gentoo}$ $\\neq$ 4000g \n\n3. Check assumptions (normal)\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#qqplot\nggplot(gentoo, aes(sample = body_mass_g))+\n  geom_qq()+\n  geom_qq_line()\n```\n\n::: {.cell-output-display}\n![](Lab05_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#boxplot\nggplot(gentoo, aes(x = body_mass_g))+\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](Lab05_files/figure-html/unnamed-chunk-30-2.png){width=672}\n:::\n\n```{.r .cell-code}\n#histogram\nggplot(gentoo, aes(x = body_mass_g))+\n  geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Lab05_files/figure-html/unnamed-chunk-30-3.png){width=672}\n:::\n\n```{.r .cell-code}\n#shapiro test\nshapiro.test(gentoo$body_mass_g)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  gentoo$body_mass_g\nW = 0.98606, p-value = 0.2605\n```\n\n\n:::\n:::\n\n\n\n\n\n> The data are normally distributed\n\n4. Calculate test statistic and\n5. Obtain P-value or critical value\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#t test\nt.test(gentoo$body_mass_g, mu = 4000)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  gentoo$body_mass_g\nt = 23.764, df = 118, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 4000\n95 percent confidence interval:\n 5001.403 5183.471\nsample estimates:\nmean of x \n 5092.437 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n6. Make statistical conclusion\n\n> p < 0.05, so we reject the null hypothesis\n\n7. Write a scientific (biological) conclusion\n\n> penguins do not weigh the same as Stevie.On average, gentoo penguins weigh 5092.437g, so they are heavier.\n\n----\n:::\n### Attribution\n\nThis lab was developed using resources that are available under a [Creative Commons Attribution 4.0 International license](http://creativecommons.org/licenses/by/4.0/), made available on the [SOLES Open Educational Resources repository](https://github.com/usyd-soles-edu/).\n\n\n\n\n\n\n::: {.cell}\n\n:::",
    "supporting": [
      "Lab05_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}