<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="The University of Sydney">

<title>Lab 12 - Non-linear models – ENVX1002 Handbook</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-1fa1d8026083a9bddc52b4aafc7f818e.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-8e00f2f28a1266a720913de837032221.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-2b359d2b6993200113079de798898405.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-21abdccd215aee3adb44e4f991220b7f.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: #000;
      }

      .quarto-title-block .quarto-title-banner {
        color: #000;
background: #FCEDE2;
      }
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="docked">

<div id="quarto-search-results"></div>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../labs/Lab01.html"><strong>🖥️ Computer labs</strong></a></li><li class="breadcrumb-item"><a href="../labs/Lab12.html">Lab 12 - Non-linear models</a></li></ol></nav>
      <h1 class="title">Lab 12 - Non-linear models</h1>
            <p class="subtitle lead"><a href="../index.html">ENVX1002 Handbook</a></p>
                  <div>
        <div class="description">
          The University of Sydney
        </div>
      </div>
                </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">Semester 1, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#before-we-begin" id="toc-before-we-begin" class="nav-link active" data-scroll-target="#before-we-begin">Before we begin</a>
  <ul class="collapse">
  <li><a href="#solution" id="toc-solution" class="nav-link" data-scroll-target="#solution">Solution</a></li>
  </ul></li>
  <li><a href="#polynomials" id="toc-polynomials" class="nav-link" data-scroll-target="#polynomials">Polynomials</a>
  <ul class="collapse">
  <li><a href="#exercise-1-interpreting-polynomials" id="toc-exercise-1-interpreting-polynomials" class="nav-link" data-scroll-target="#exercise-1-interpreting-polynomials">Exercise 1: Interpreting polynomials</a></li>
  <li><a href="#solution-1" id="toc-solution-1" class="nav-link" data-scroll-target="#solution-1">Solution</a></li>
  <li><a href="#solution-2" id="toc-solution-2" class="nav-link" data-scroll-target="#solution-2">Solution</a></li>
  <li><a href="#solution-3" id="toc-solution-3" class="nav-link" data-scroll-target="#solution-3">Solution</a></li>
  <li><a href="#exercise-2-fitting-polynomials-in-r" id="toc-exercise-2-fitting-polynomials-in-r" class="nav-link" data-scroll-target="#exercise-2-fitting-polynomials-in-r">Exercise 2: Fitting polynomials in R</a></li>
  <li><a href="#solution-4" id="toc-solution-4" class="nav-link" data-scroll-target="#solution-4">Solution</a></li>
  <li><a href="#solution-5" id="toc-solution-5" class="nav-link" data-scroll-target="#solution-5">Solution</a></li>
  </ul></li>
  <li><a href="#exponential-function" id="toc-exponential-function" class="nav-link" data-scroll-target="#exponential-function">Exponential function</a>
  <ul class="collapse">
  <li><a href="#exercise-3-initial-estimates-for-exponential-growth-function" id="toc-exercise-3-initial-estimates-for-exponential-growth-function" class="nav-link" data-scroll-target="#exercise-3-initial-estimates-for-exponential-growth-function">Exercise 3: Initial estimates for exponential growth function</a></li>
  <li><a href="#solution-6" id="toc-solution-6" class="nav-link" data-scroll-target="#solution-6">Solution</a></li>
  <li><a href="#solution-7" id="toc-solution-7" class="nav-link" data-scroll-target="#solution-7">Solution</a></li>
  <li><a href="#solution-8" id="toc-solution-8" class="nav-link" data-scroll-target="#solution-8">Solution</a></li>
  <li><a href="#solution-9" id="toc-solution-9" class="nav-link" data-scroll-target="#solution-9">Solution</a></li>
  <li><a href="#exercise-4-exponential-growth-models" id="toc-exercise-4-exponential-growth-models" class="nav-link" data-scroll-target="#exercise-4-exponential-growth-models">Exercise 4 : Exponential growth models</a></li>
  <li><a href="#solution-10" id="toc-solution-10" class="nav-link" data-scroll-target="#solution-10">Solution</a></li>
  <li><a href="#solution-11" id="toc-solution-11" class="nav-link" data-scroll-target="#solution-11">Solution</a></li>
  <li><a href="#solution-12" id="toc-solution-12" class="nav-link" data-scroll-target="#solution-12">Solution</a></li>
  </ul></li>
  <li><a href="#logistic-function" id="toc-logistic-function" class="nav-link" data-scroll-target="#logistic-function">Logistic function</a>
  <ul class="collapse">
  <li><a href="#exercise-5-logistic-models" id="toc-exercise-5-logistic-models" class="nav-link" data-scroll-target="#exercise-5-logistic-models">Exercise 5: Logistic models</a></li>
  <li><a href="#solution-13" id="toc-solution-13" class="nav-link" data-scroll-target="#solution-13">Solution</a></li>
  <li><a href="#solution-14" id="toc-solution-14" class="nav-link" data-scroll-target="#solution-14">Solution</a></li>
  <li><a href="#solution-15" id="toc-solution-15" class="nav-link" data-scroll-target="#solution-15">Solution</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Lab12.pdf"><i class="bi bi-file-pdf"></i>Typst</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Learning outcomes
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Calculate “by hand” the initial estimates of the parameters of a non-linear model</li>
<li>Interpret tables of regression coefficients for polynomials to perform hypothesis testing</li>
<li>Fit polynomials and non-linear models to data using least-squares fitting using the SOLVER add-in in Excel</li>
<li>Fit polynomials and non-linear models to data in R, and interpret the outputs</li>
</ul>
</div>
</div>
<section id="before-we-begin" class="level2">
<h2 class="anchored" data-anchor-id="before-we-begin">Before we begin</h2>
<p>Create your Quarto document and save it as <code>Lab-12.qmd</code> or similar.</p>
<p>The following data files are required:</p>
<ol type="1">
<li><a href="data/east_creek.csv">east_creek.csv</a></li>
</ol>
<p>Over the past few weeks you have explored linear models and how to interpret model summary output. Again we have stepped up the complexity, now venturing into the world of non-linear models.</p>
<p>This practical focuses on fitting non-linear models to data with an emphasis on 3 important classes of functions that all budding biologists and environmental scientists should know</p>
<ul>
<li>polynomials,</li>
<li>exponential models, and</li>
<li>logistic models.</li>
</ul>
<p><strong>A question before we begin:</strong></p>
<p>What are some advantages and disadvantages of non-linear models as compared to polynomials?</p>
<section id="solution" class="level3" style="color:green;">
<h3 style="color:green;" class="anchored" data-anchor-id="solution">Solution</h3>
<hr>
<table class="caption-top table">
<colgroup>
<col style="width: 59%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Polynomials</th>
<th>Non-linear models(exponential/logistic)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Parameters hard to interpret</td>
<td>Parameters interpretable in terms of biological and environmental processes</td>
</tr>
<tr class="even">
<td>Can be fitted with analytical or numerical methods</td>
<td>Fitting parameters can be difficult as use numerical methods which rely on good initial estimates of parameters</td>
</tr>
<tr class="odd">
<td>Hypothesis testing and estimating R<sup>2</sup> straightforward</td>
<td>Hypothesis testing and estimating R<sup>2</sup> is a bit more difficult – not absence of R<sup>2</sup> in R output</td>
</tr>
<tr class="even">
<td>Difficult to model horizontal asymptotes</td>
<td>Can accommodate horizontal asymptotes</td>
</tr>
<tr class="odd">
<td>Only polynomials of even order restricted to positive values</td>
<td>Constrained to positive values</td>
</tr>
</tbody>
</table>
<hr>
<p><br></p>
</section>
</section>
<section id="polynomials" class="level2">
<h2 class="anchored" data-anchor-id="polynomials">Polynomials</h2>
<div class="pad-box-mini" style="background-color: #f2f2f2; padding:10px;">
<p><strong>Quadratic</strong></p>
<p><span class="math inline">\(y = \beta_0 + \beta_1 x + \beta_2 x^2\)</span></p>
<p>where the parameters are the y-intercept (<em>b<sub>0</sub></em>), the linear component (<em>b<sub>1</sub></em>) and the quadratic component (<em>b<sub>2</sub></em>).</p>
<p>If <em>b<sub>2</sub></em> is negative then the shape of the function is convex upwards, i.e.&nbsp;<em>y</em> increases with <em>x</em> until reaches a peak and then <em>y</em> decreases.</p>
<p>It is easy to understand so it has been commonly used for modelling the response of yield to inputs such as fertiliser, seeding rates. This is despite much criticism for being unrealistic.</p>
<p>Limitations:</p>
<ol type="i">
<li><p>rate of increase to peak is same as rate of decrease past peak</p></li>
<li><p>does not level off as <em>x</em> becomes small or very large, <em>y</em> just keeps increasing or decreasing.</p></li>
</ol>
<p><strong>Cubic</strong></p>
<p><span class="math inline">\(y = \beta_0 + \beta_1 x + \beta_2 x^2 + \beta_3 x^3\)</span></p>
<p>Compared to the quadratic model which has 1 turning point, a cubic model has 2 turning points.</p>
</div>
<p><br></p>
<section id="exercise-1-interpreting-polynomials" class="level3">
<h3 class="anchored" data-anchor-id="exercise-1-interpreting-polynomials">Exercise 1: Interpreting polynomials</h3>
<p>A study was performed to examine the soil properties that control the within-field variation in crop yield. The focus of this question is on soil pH which (among other things) controls the availability of nutrients to plants.</p>
<p>This exercise does not require you to read in any data, but rather focus on interpreting the model output and comparing the models.</p>
<p>The figure below shows the raw observations of yield plotted against pH with three models fitted; a linear model, quadratic polynomial and a cubic polynomial.</p>
<ol type="a">
<li>which line corresponds to which model?</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab12_files/figure-html/LoadData-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="solution-1" class="level3" style="color:green;">
<h3 style="color:green;" class="anchored" data-anchor-id="solution-1">Solution</h3>
<hr>
<p><strong>a)</strong></p>
<ul>
<li>The blue line is the linear model – it is straight.</li>
</ul>
<p>Note: If the quadratic or higher order terms are very small for some values of the predictor the line could also appear to be straight.</p>
<ul>
<li><p>The red line is the quadratic, it has one turning point (~pH = 7.4) where the slope of the line = 0.</p></li>
<li><p>The black line is the cubic, it has two turning points, one is around pH ~ 7.5, the other is not on the range of the plot but you can see that the curve is changing direction and bending up at a pH of ~ 6.8, as it transitions from concave down to concave up as values get smaller. This is useful as it allows for a gentler increase in the slope of the fitted line at smaller values of pH.</p></li>
</ul>
<hr>
<ol start="2" type="a">
<li>based on the output from the 3 models below, which model fits the data best? Note: no hypothesis testing yet, just how well the model fits the data (R<sup>2</sup>).</li>
</ol>
<!-- -->
<ol type="1">
<li>Linear model:</li>
</ol>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = yield ~ ph, data = soil)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.0027 -0.5540  0.2189  0.7643  1.9424 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)  7.08842    3.05279   2.322   0.0221 *
ph          -0.05249    0.40438  -0.130   0.8970  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.137 on 108 degrees of freedom
Multiple R-squared:  0.000156,  Adjusted R-squared:  -0.009102 
F-statistic: 0.01685 on 1 and 108 DF,  p-value: 0.897</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Quadratic model:</li>
</ol>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = yield ~ ph + I(ph^2), data = soil)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.5010 -0.4380 -0.0099  0.5871  1.7064 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -299.9031    54.2430  -5.529 2.30e-07 ***
ph            83.1948    14.6954   5.661 1.27e-07 ***
I(ph^2)       -5.6336     0.9942  -5.667 1.24e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.002 on 107 degrees of freedom
Multiple R-squared:  0.2309,    Adjusted R-squared:  0.2166 
F-statistic: 16.07 on 2 and 107 DF,  p-value: 7.921e-07</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Cubic model:</li>
</ol>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = yield ~ ph + I(ph^2) + I(ph^3), data = soil)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.3734 -0.4540  0.0526  0.5171  1.9561 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) 1719.020   1082.451   1.588   0.1152  
ph          -745.066    443.767  -1.679   0.0961 .
I(ph^2)      107.461     60.570   1.774   0.0789 .
I(ph^3)       -5.140      2.752  -1.867   0.0646 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9908 on 106 degrees of freedom
Multiple R-squared:  0.2554,    Adjusted R-squared:  0.2344 
F-statistic: 12.12 on 3 and 106 DF,  p-value: 6.971e-07</code></pre>
</div>
</div>
</section>
<section id="solution-2" class="level3" style="color:green;">
<h3 style="color:green;" class="anchored" data-anchor-id="solution-2">Solution</h3>
<hr>
<p><strong>b)</strong> The R<sup>2</sup> assesses how well the model fits the data. The best model based on this metric is the cubic polynomial (R<sup>2</sup> = 0.255), then the quadratic polynomial (R<sup>2</sup> = 0.231) and finally the linear model (R<sup>2</sup> = 0.00016).</p>
<p>It should be noted that this does not consider the model complexity (i.e.&nbsp;aiming for the most parsimonious model - the one with least predictors). For example, is the extra complexity of the cubic polynomial worth an increase in R<sup>2</sup> of 0.024? Formal hypothesis testing can address this question.</p>
<hr>
<p><br></p>
<ol start="3" type="a">
<li>Use the R output to perform hypothesis testing to find the best model. Write out the hypotheses you are testing.</li>
</ol>
</section>
<section id="solution-3" class="level3" style="color:green;">
<h3 style="color:green;" class="anchored" data-anchor-id="solution-3">Solution</h3>
<hr>
<p><strong>c)</strong> The general approach is to start with the most complex model and work backwards to the simplest model.</p>
<p>First we examine the cubic polynomial and more specifically the cubic term (the most complex term) where the hypotheses we are testing are:</p>
<p>H<sub>0</sub>: <span class="math inline">\(\beta_3 = 0\)</span>,</p>
<p>H<sub>1</sub>: <span class="math inline">\(\beta_3 \neq 0\)</span></p>
<p>The line of R output that addresses this is the 4th line of the coefficients table (i.e.&nbsp;highest order):</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>               Estimate  Std. Error   t value   Pr(&gt;|t|)
(Intercept) 1719.019609 1082.450919  1.588081 0.11524654
ph          -745.065927  443.766859 -1.678958 0.09610580
I(ph^2)      107.461212   60.569624  1.774177 0.07890512
I(ph^3)       -5.140059    2.752473 -1.867433 0.06460381</code></pre>
</div>
</div>
<p>The P-value is &gt; 0.05 so we fail to reject the null hypothesis. This means we should remove the cubic term.</p>
<p>Note that the estimates of the quadratic and linear terms are conditional on the cubic term also being in the model so will change if we fit a quadratic polynomial (see the R output).</p>
<p>Next we consider the quadratic polynomial model:</p>
<p>H<sub>0</sub>: <span class="math inline">\(\beta_2 = 0\)</span>,</p>
<p>H<sub>1</sub>: <span class="math inline">\(\beta_2 \neq 0\)</span></p>
<p>The line of R output that addresses this is the 3rd line of the coefficients table (i.e.&nbsp;highest order):</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>               Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept) -299.903051 54.2429517 -5.528885 2.296782e-07
ph            83.194759 14.6953503  5.661298 1.272952e-07
I(ph^2)       -5.633609  0.9941893 -5.666536 1.243405e-07</code></pre>
</div>
</div>
<p>The P-value is &lt; 0.05 so we reject the null hypothesis and would keep the quadratic term in the model. The best model to use is the quadratic polynomial.</p>
<p>Note that the linear term is also significant but even if it were not, we would keep it in the model as in most situations it is hard to justify a situation where a biological or environmental process could be modelled by a quadratic term alone.</p>
<p>In summary for polynomials we only test the highest order term in each polynomial in deciding whether to keep use the polynomial at all.</p>
<hr>
<p><br></p>
</section>
<section id="exercise-2-fitting-polynomials-in-r" class="level3">
<h3 class="anchored" data-anchor-id="exercise-2-fitting-polynomials-in-r">Exercise 2: Fitting polynomials in R</h3>
<p>This exercise will use real data from a yield-fertiliser trial in Bedfordshire, United Kingdom.</p>
<p>First thing we can do is fit a linear model to the fertiliser data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create fertiliser and yield objects</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>fert <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>, <span class="dv">170</span>, <span class="dv">225</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>yield <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">3.32</span>, <span class="fl">5.23</span>, <span class="fl">5.41</span>, <span class="fl">5.02</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Fits a linear model and saves it to an object called lin.mod</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>lin.mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> fert)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarises key features of model</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lin.mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = yield ~ fert)

Residuals:
      1       2       3       4 
-0.4469  0.6727  0.2995 -0.5252 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) 3.766929   0.634765   5.934   0.0272 *
fert        0.007904   0.004243   1.863   0.2035  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7134 on 2 degrees of freedom
Multiple R-squared:  0.6344,    Adjusted R-squared:  0.4515 
F-statistic:  3.47 on 1 and 2 DF,  p-value: 0.2035</code></pre>
</div>
</div>
<ol type="a">
<li>What is the model fit like in this model?</li>
</ol>
</section>
<section id="solution-4" class="level3" style="color:green;">
<h3 style="color:green;" class="anchored" data-anchor-id="solution-4">Solution</h3>
<hr>
<p><strong>a)</strong> Our model fit is ok, with R<sup>2</sup> of 0.6344.</p>
<hr>
<p>Fit and plot a quadratic polynomial in R. In R a quadratic polynomial can be fitted using the following lines of code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a new variable which is the square of the fertilizer rates</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>fert2 <span class="ot">&lt;-</span> fert<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># fit the quadratic model incorporating fert2</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>quad.mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield <span class="sc">~</span> fert <span class="sc">+</span> fert2)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(quad.mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = yield ~ fert + fert2)

Residuals:
        1         2         3         4 
-0.005611  0.024528 -0.032791  0.013874 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)  3.326e+00  4.324e-02   76.92  0.00828 **
fert         2.786e-02  9.014e-04   30.91  0.02059 * 
fert2       -9.064e-05  3.921e-06  -23.12  0.02752 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.0436 on 1 degrees of freedom
Multiple R-squared:  0.9993,    Adjusted R-squared:  0.998 
F-statistic: 731.7 on 2 and 1 DF,  p-value: 0.02613</code></pre>
</div>
</div>
<ol start="2" type="a">
<li>What is the fit like for our quadratic model? is it better than our linear model?</li>
</ol>
</section>
<section id="solution-5" class="level3" style="color:green;">
<h3 style="color:green;" class="anchored" data-anchor-id="solution-5">Solution</h3>
<hr>
<p><strong>b)</strong> Our model fit even better, with R<sup>2</sup> of 0.9993.</p>
<hr>
<p>In Excel it is easy to fit a line, by creating a scatterplot, then <strong>add Trendline…</strong> and selecting <strong>Polynomial</strong> (2nd order).</p>
<p>To fit our polynomial line in R, we need to obtain model predictions first.</p>
<p>To plot model predictions you first need to predict at fine intervals of the predictor to make a continuous plot that is not jagged or stepped. To create a new prediction dataset you can use the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># creates a sequence of numbers from 0 to 225 going up in increments of 1</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>new.fert <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">225</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can use our model to predict at the values in the new prediction dataset, in this case <code>new.fert</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>new.pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(quad.mod, <span class="fu">list</span>(<span class="at">fert =</span> new.fert, <span class="at">fert2 =</span> new.fert<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The general form of the <code>predict</code> function is <code>predict(model object, list object)</code>.</p>
<p>The list object tells R what object contains the data we will use to predict. For example in our case the model was built on fert and fert2 so we have to tell the predict function what object contains the new values for each of these, in our case new.fert.</p>
<p>Now we plot the raw observation as points and add an overlay of the model fit as lines:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fert, yield, <span class="at">xlab =</span> <span class="st">"Fertilizer"</span>, <span class="at">ylab =</span> <span class="st">"Yield"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(new.fert, new.pred) <span class="co"># Adds lines to original plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab12_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</section>
</section>
<section id="exponential-function" class="level2">
<h2 class="anchored" data-anchor-id="exponential-function">Exponential function</h2>
<div class="pad-box-mini" style="background-color: #f2f2f2; padding:10px;">
<p><span class="math inline">\(y=y_0e^{kx}\)</span></p>
<p>where the parameters are <em>y<sub>0</sub></em> which is the multiplier which expresses the starting or final value, and <em>k</em> which is negative for exponential decay and positive for the exponential growth.</p>
<p>The half life (for decay) or doubling time (for growth) can be calculated as</p>
<p><span class="math inline">\(\frac{log_e 2}{k}\)</span></p>
<p>Limitations:</p>
<ol type="i">
<li><p>harder to fit than polynomials</p></li>
<li><p>exponential growth has no horizontal asymptote; keeps going up.</p></li>
</ol>
</div>
<p><br></p>
<section id="exercise-3-initial-estimates-for-exponential-growth-function" class="level3">
<h3 class="anchored" data-anchor-id="exercise-3-initial-estimates-for-exponential-growth-function">Exercise 3: Initial estimates for exponential growth function</h3>
<p>In this exercise we will find initial estimates of the parameters of an exponential growth model by visual assessment of plots of the data and/or rough calculations. The initial estimates of the parameters are needed as starting points for the iterative fitting methods we will use in the practicals, e.g.&nbsp;SOLVER in Excel and the <code>nls()</code> function in R.</p>
<p>The plot and table below presents the population of the world from 1650-1965.</p>
<p>We wish to model the data with an exponential growth function of the form;</p>
<p><span class="math inline">\(y=y_0e^{kx}\)</span></p>
<p>where</p>
<ul>
<li><p><em>y</em> is the population in the year <em>x</em>,</p></li>
<li><p>y<sub>0</sub> is the population in 1650 and</p></li>
<li><p><em>k</em> is the rate constant.</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab12_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<tbody>
<tr class="odd">
<td style="text-align: left;">Year</td>
<td style="text-align: left;">1650</td>
<td style="text-align: left;">1750</td>
<td style="text-align: left;">1804</td>
<td style="text-align: left;">1850</td>
<td style="text-align: left;">1900</td>
<td style="text-align: left;">1927</td>
<td style="text-align: left;">1950</td>
<td style="text-align: left;">1955</td>
<td style="text-align: left;">1960</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pop (billions)</td>
<td style="text-align: left;">0.5</td>
<td style="text-align: left;">0.7</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">1.2</td>
<td style="text-align: left;">1.6</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">2.55</td>
<td style="text-align: left;">2.88</td>
<td style="text-align: left;">3</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br></p>
<ol type="a">
<li>Provide an initial estimate of y<sub>0</sub>.</li>
</ol>
</section>
<section id="solution-6" class="level3" style="color:green;">
<h3 style="color:green;" class="anchored" data-anchor-id="solution-6">Solution</h3>
<hr>
<p><strong>a)</strong> Use the first measurement, in 1650 the world population was 0.5 billion.</p>
<hr>
<p>The parameter <em>k</em> can be estimated from a linear model fitted to log<sub>e</sub> population against year.</p>
<p>Rather than formally fitting a linear model you could estimate the slope approximately by using the smallest and largest value to estimate the slope and therefore <em>k</em>.</p>
<ol start="2" type="a">
<li>Use this approach to estimate k.</li>
</ol>
<p>Hint: <span class="math display">\[
slope = k = \frac{log_e y_{max} - log_e y_{min}}{x_{max} - x_{min}}
\]</span></p>
</section>
<section id="solution-7" class="level3" style="color:green;">
<h3 style="color:green;" class="anchored" data-anchor-id="solution-7">Solution</h3>
<hr>
<p><strong>b)</strong> The smallest value is 0.5 in 1650 and the largest value is 3 billion in 1960.</p>
<p>We log<sub>e</sub> the population values and calculate the slope of the line between the 2 observations. The slope is an estimate of k:</p>
<p><span class="math display">\[
slope = k = \frac{log_e 3 - log_e 0.5}{1960-1650} = \frac{1.792}{310}  = 0.00577987
\]</span></p>
<hr>
<ol start="3" type="a">
<li>For an exponential growth model the doubling time of a population can be estimated by log<sub>e</sub>2 /k.</li>
</ol>
<p>Examine the graph and/or table to estimate the doubling time and use this to estimate <em>k</em>. You will have to make <em>k</em> the subject in the equation for estimating the doubling time.</p>
</section>
<section id="solution-8" class="level3" style="color:green;">
<h3 style="color:green;" class="anchored" data-anchor-id="solution-8">Solution</h3>
<hr>
<p><strong>c)</strong> The smallest value is 0.5 in 1650 and the year it has doubled (1 billion) is in 1804.</p>
<p>Using the difference between the two years, we can solve for <em>k</em> :</p>
<p>1804-1650 = 154</p>
<p><span class="math inline">\(154 = \frac{log_e 2}{k}\)</span> ; multiply both sides by <em>k</em></p>
<p><span class="math inline">\(154k = log_e 2\)</span> ; divide both sides by 154</p>
<p><span class="math inline">\(k = \frac{log_e 2}{154} = 0.004501\)</span></p>
<p>Alternatively, you can also use the slope calculation to obtain <em>k</em> for the doubling time:</p>
<p><span class="math display">\[
slope = k = \frac{log_e 1 - log_e 0.5}{1804-1650} = \frac{0.693}{154}  = 0.004501
\]</span></p>
<hr>
<ol start="4" type="a">
<li>How similar were the estimates of <em>k</em>?</li>
</ol>
</section>
<section id="solution-9" class="level3" style="color:green;">
<h3 style="color:green;" class="anchored" data-anchor-id="solution-9">Solution</h3>
<hr>
<p><strong>d)</strong> Both estimates are of a similar magnitude. It should be noted that the estimate of the slope (b1) is an approximation. If we formally estimate the slope (<code>lm(log(pop)~year</code>) the value is 0.005835.</p>
<hr>
<p><br></p>
</section>
<section id="exercise-4-exponential-growth-models" class="level3">
<h3 class="anchored" data-anchor-id="exercise-4-exponential-growth-models">Exercise 4 : Exponential growth models</h3>
<p>This data is from Jenkins &amp; Adams (2010) who studied soil respiration rates against temperature for different vegetation communities in the Snowy Mountains. They fitted an exponential growth model to the data.</p>
<p>The purpose of this exercise is to illustrate the dangers of using Excel’s in-built functions for statistics more complex than calculating means and fitting simple models.</p>
<p>Plot the data in Excel and using the <strong>Add Trendline…</strong> option. Make sure tick the option for displaying the equation in the graph.</p>
<ol type="a">
<li>The researchers performed the experiment up to a temperature of 40 degrees C, would you expect exponential growth in the respiration rate to continue if high temperatures were considered? Is there a better model?</li>
</ol>
</section>
<section id="solution-10" class="level3" style="color:green;">
<h3 style="color:green;" class="anchored" data-anchor-id="solution-10">Solution</h3>
<hr>
<p><strong>a)</strong> Eventually it would get too hot and the microbes which cause soil respiration would start to “die” or the community structure would change.</p>
<p>Some sort of horizontal asymptote could be reached, which could be modelled by a logistic model, or a decline is needed after a peak; there are non-linear models that accommodate such data that follows such a pattern.</p>
<hr>
<p>Now fit the same model in R using the nls function. Code to get you started is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>temp<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">10</span>,<span class="dv">20</span>,<span class="dv">25</span>,<span class="dv">30</span>,<span class="dv">35</span>,<span class="dv">40</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>respiration<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">8</span>,<span class="dv">11</span>,<span class="dv">18</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="do">##Initial parameters</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>exp.mod<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="at">y0=</span><span class="fl">1.0</span>,<span class="at">k=</span><span class="fl">0.1</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="do">##Fits exponential model</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>res.exp<span class="ot">&lt;-</span><span class="fu">nls</span>(respiration <span class="sc">~</span> y0 <span class="sc">*</span> <span class="fu">exp</span>(k<span class="sc">*</span>temp), <span class="at">start=</span>exp.mod,<span class="at">trace=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2025.224    (3.23e+01): par = (1 0.1)
90.64319    (7.34e+00): par = (0.6559559 0.09162898)
2.841421    (9.49e-01): par = (0.7302258 0.08091595)
1.488431    (5.63e-02): par = (0.7944381 0.07731867)
1.483685    (1.52e-03): par = (0.8033809 0.07707711)
1.483681    (4.12e-05): par = (0.8036903 0.07706805)
1.483681    (1.68e-06): par = (0.8037011 0.07706768)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Summarise model</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(res.exp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Formula: respiration ~ y0 * exp(k * temp)

Parameters:
   Estimate Std. Error t value Pr(&gt;|t|)    
y0 0.803701   0.118632   6.775  0.00107 ** 
k  0.077068   0.004048  19.037 7.37e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5447 on 5 degrees of freedom

Number of iterations to convergence: 6 
Achieved convergence tolerance: 1.681e-06</code></pre>
</div>
</div>
<ol start="2" type="a">
<li>Now you can fit a line to the plot. Does this look similar to your trendline in Excel?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plots raw data</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(temp,respiration,<span class="at">xlab=</span><span class="st">'Temperature'</span>,<span class="at">ylab=</span><span class="st">'Respiration'</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Creates new dataset for predictions ( 5 to 40 at an interval of 1)</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>temp.new<span class="ot">&lt;-</span><span class="fu">seq</span>(<span class="dv">5</span>,<span class="dv">40</span>,<span class="dv">1</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Makes predictions onto temp.new</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>pred.exp<span class="ot">&lt;-</span><span class="fu">predict</span>(res.exp,<span class="fu">list</span>(<span class="at">temp=</span>temp.new))</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="co">#Adds model fit to existing plots</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span> (temp.new,pred.exp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab12_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="solution-11" class="level3" style="color:green;">
<h3 style="color:green;" class="anchored" data-anchor-id="solution-11">Solution</h3>
<hr>
<p><strong>b)</strong> Yes, they do look similar.</p>
<hr>
<p>Compare the parameters values between Excel and R. You can extract the RSS value from an <code>nls</code> object by using the code below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">deviance</span>(res.exp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.483681</code></pre>
</div>
</div>
<ol start="3" type="a">
<li>Calculate the RSS value for the Excel exponential model. Based on this, which is the better model?</li>
</ol>
</section>
<section id="solution-12" class="level3" style="color:green;">
<h3 style="color:green;" class="anchored" data-anchor-id="solution-12">Solution</h3>
<hr>
<p><strong>c)</strong> The better model is the one fitted in R which is optimized to fit the actual observations rather than the approximate linearisation approach used by Excel.</p>
<hr>
<p>When faced with the need to fit an exponential function, one approach that was used before computing power became readily accessible was to log the <em>y</em> values which linearises the relationship with <em>x</em>, enabling the modeller to use a simple linear model.</p>
<p>If we linearise, model would be <span class="math inline">\(log_e(y) = b_0 + b_1x\)</span>, where <span class="math inline">\(e^{b_0}\)</span> is the <em>y<sub>0</sub></em> parameter in an exponential model, and <em>b<sub>1</sub></em> is the <em>k</em> parameter in the exponential model. This is similar to what was demonstrated in the lecture this week.</p>
<p>In Excel, log the soil respiration data and fit a linear model. You will see that the fitted model gives the same values as the exponential model fitted to the untransformed data.</p>
<p>If you compare the R<sup>2</sup> values for both you will see they are the same. This means that Excel reports the R<sup>2</sup> of the linear model fitted to logged respiration as the R<sup>2</sup> of the exponential model fitted to the raw data. This is naughty of Excel.</p>
<div class="pad-box-mini" style="background-color: #f2f2f2; padding:10px;">
<p>For the dataset used here the exponential model fits it so well the Excel approach is only slightly different to the correct approach used in R.</p>
<p>In cases where the model does not fit the data so well the differences would be larger. Logarithm makes smaller values larger and larger values smaller.</p>
<p><strong>WHY IS THIS SUB-OPTIMAL?</strong></p>
<ul>
<li><p>Regression modelling assumes that the residuals are normally distributed so logging normally distributed data will change the distribution to a non-normal one – it is best to analyse the data without transformation.</p></li>
<li><p>Modelling data on the logged scale reduces the impact that larger values have on minimising the RSS but when you plot the fitted model with the original data you may observe large discrepancies for larger values. In other words, using a linear model on the log(data) can result in a higher discrepancy for larger values when plotting the fitted model on the original data. Therefore, the model fitted to the logged data is not necessarily the best on the original data.</p></li>
<li><p>The reporting of the R-squared on the logged data on a model purported to be fitted to untransformed data is just wrong as the R-squared on the log scale will be better as the variation in the data has been reduced but we really want to know how well an exponential model fits the raw data.</p></li>
</ul>
</div>
<p><br></p>
</section>
</section>
<section id="logistic-function" class="level2">
<h2 class="anchored" data-anchor-id="logistic-function">Logistic function</h2>
<div class="pad-box-mini" style="background-color: #f2f2f2; padding:10px;">
<p>There are several versions of the logistic function. We will use the following:</p>
<p><span class="math display">\[ y = \frac{Asym}{1+e^{\frac{xmid-x}{scal}}} \]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(Asym\)</span> is the maximum value of <span class="math inline">\(y\)</span> (upper limit, horizontal asymptote).</li>
<li><span class="math inline">\(xmid\)</span> is the value of <span class="math inline">\(x\)</span> when <span class="math inline">\(y\)</span> is halfway between the lower and upper limits (inflection point, <span class="math inline">\(y = 0.5 \times Asym\)</span>).</li>
<li><span class="math inline">\(scal\)</span> is the rate of change: the rate at which <span class="math inline">\(y\)</span> approaches the upper limit.</li>
</ul>
<p>Commonly used to model growth that has a sigmoid shape, i.e.&nbsp;where growth is initially slow, then picks up to a maximum, then slows down again as the system reaches a maximum.</p>
<p>Limitations:</p>
<p>Harder to fit than polynomials.</p>
</div>
<p><br></p>
<section id="exercise-5-logistic-models" class="level3">
<h3 class="anchored" data-anchor-id="exercise-5-logistic-models">Exercise 5: Logistic models</h3>
<p>In this exercise you will model the yield of pasture over time (since sowing).</p>
<p>Note, we will assume the yield at sowing = 0 is 0 t/ha, which allows us to use the equation above (that is pre-defined in <code>SSlogis()</code>).</p>
<p>If this were not the case, we would need to use a slightly different equation; <span class="math inline">\(y = y_0 + \frac{Asym}{1+e^{-scal(x-xmid)}}\)</span>, where <span class="math inline">\(y_0\)</span> is the yield at sowing.</p>
<ol type="a">
<li>Fit the model in R using the <code>nls</code> function. Estimate the starting<br>
parameters manually (using the previous exercise and the equation above as a guide). Then use the <code>SSlogis()</code> function to automatically estimate the parameters (see L12, Tut12 or the <a href="https://envx-resources.github.io/ENVX1002-handbook/module03/043-nonlinear.html">handbook</a>).</li>
</ol>
</section>
<section id="solution-13" class="level3" style="color:green;">
<h3 style="color:green;" class="anchored" data-anchor-id="solution-13">Solution</h3>
<hr>
<p><strong>a)</strong> Use the following code to read in the code and run the model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Data input</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>week <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">9</span>,<span class="dv">14</span>,<span class="dv">21</span>,<span class="dv">28</span>,<span class="dv">42</span>,<span class="dv">57</span>,<span class="dv">63</span>,<span class="dv">70</span>,<span class="dv">79</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>yield <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">8.93</span>,<span class="fl">10.80</span>,<span class="fl">18.59</span>,<span class="fl">22.33</span>,<span class="fl">39.35</span>,<span class="fl">56.11</span>,<span class="fl">61.73</span>,<span class="fl">64.62</span>,<span class="fl">67.08</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimating parameters</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>log.mod <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">Asym=</span><span class="fl">70.0</span>, <span class="at">xmid=</span><span class="fl">40.0</span>, <span class="at">scal=</span><span class="fl">1.0</span>)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>yld.log <span class="ot">&lt;-</span> <span class="fu">nls</span>(yield <span class="sc">~</span> Asym<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>((xmid <span class="sc">-</span> week)<span class="sc">/</span>scal)), <span class="at">start =</span> log.mod, <span class="at">trace=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1836.927    (1.43e+00): par = (70 40 1)
1124.107    (4.86e+00): par = (69.9852 25.47246 8.26585)
1115.702    (4.87e+00): par = (69.96521 25.49818 8.285329)
1099.053    (4.91e+00): par = (69.92565 25.54971 8.324271)
1066.386    (4.99e+00): par = (69.84821 25.65308 8.402085)
1003.516    (5.15e+00): par = (69.70002 25.86098 8.557394)
887.1432    (5.47e+00): par = (69.42984 26.28115 8.866419)
688.2579    (6.13e+00): par = (68.98988 27.13636 9.475723)
400.9711    (6.89e+00): par = (68.47614 28.88513 10.64292)
116.6069    (4.13e+00): par = (68.626 32.37177 12.67415)
12.30649    (7.23e-01): par = (71.36289 38.10072 15.12695)
8.059833    (2.07e-02): par = (72.51167 38.91436 14.87333)
8.056533    (1.15e-03): par = (72.45789 38.86434 14.84398)
8.056523    (7.26e-05): par = (72.46251 38.86759 14.8459)
8.056523    (4.57e-06): par = (72.46222 38.86739 14.84577)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Self-starting function</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>yld.log <span class="ot">&lt;-</span> <span class="fu">nls</span>(yield <span class="sc">~</span> <span class="fu">SSlogis</span>(week, Asym, xmid, scal))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<ol start="2" type="a">
<li>Plot the fitted model with the observations.</li>
</ol>
</section>
<section id="solution-14" class="level3" style="color:green;">
<h3 style="color:green;" class="anchored" data-anchor-id="solution-14">Solution</h3>
<hr>
<p><strong>b)</strong> Use the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creates new dataset for predictions (5 to 40 at an interval of 1)</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>week.new <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">80</span>,<span class="dv">1</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Makes predictions onto temp.new</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>pred.log <span class="ot">&lt;-</span> <span class="fu">predict</span>(yld.log, <span class="fu">list</span>(<span class="at">week =</span> week.new))</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Adds model fit to existing plots</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(week, yield,</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">'Time (weeks)'</span>, <span class="at">ylab=</span><span class="st">'Yield (kg)'</span>)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(week.new, pred.log)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab12_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="do">## In ggplot</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ggplot(data = data.frame(week, yield), aes(x = week, y = yield)) +</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   geom_point() +</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co">#   geom_line(y = predict(yld.log, week.new), color = "red")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<ol start="3" type="a">
<li>Compare the final model parameters when we provide starting estimates, and when we use <code>SSlogis()</code>. Are they the same?</li>
</ol>
</section>
<section id="solution-15" class="level3" style="color:green;">
<h3 style="color:green;" class="anchored" data-anchor-id="solution-15">Solution</h3>
<hr>
<p><strong>c)</strong> From the code below we can see the estimated parameters are 72.46 for <span class="math inline">\(Asym\)</span>, 38.87 for <span class="math inline">\(xmid\)</span> and 14.85 for <span class="math inline">\(scal\)</span>. This should be similar to what Solver obtains in Excel.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Examine model</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(yld.log)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Formula: yield ~ SSlogis(week, Asym, xmid, scal)

Parameters:
     Estimate Std. Error t value Pr(&gt;|t|)    
Asym  72.4622     1.7340   41.79 1.26e-08 ***
xmid  38.8674     1.1794   32.95 5.19e-08 ***
scal  14.8458     0.7596   19.54 1.16e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.159 on 6 degrees of freedom

Number of iterations to convergence: 1 
Achieved convergence tolerance: 1.11e-06</code></pre>
</div>
</div>
<hr>
<div class="pad-box-mini" style="background-color: #f2f2f2; padding:10px;">
<p><strong>STARTING VALUES</strong></p>
<p>When fitting non-linear functions (i.e.&nbsp;logistic or exponential) using iterative procedures such as <code>nls</code> or SOLVER the starting estimates of the parameters need to be approximated. If the values are too far, the model will not run and return an error.</p>
<p>The best way to ensure that you have suitable starting values is to plot the data with the predictions overlaid for your starting parameters. You can then see how close your initial model is to the data.</p>
<p>The reason we go through the process of estimating parameters is because <code>nls</code> and SOLVER can fit <em>any</em> nonlinear equation. They are more versatile</p>
<p>Realistically, most nonlinear relationships you would fit are covered by a self-starting function; i.e.&nbsp;<code>SSlogis()</code>, <code>SSasymp()</code>, or <code>nlraa::SSexpf()</code>. These estimate the parameters for you and are more efficient to run. We recommend using these when suitable.</p>
</div>
<p><br></p>
<p>That’s it for Module 3! Great work exploring non-linear models!</p>
<p>Thank you all (students and demonstrators!) for your hard work and enthusiasm throughout this Module. Good luck with Project 3 and the final exam!</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/ENVX-resources\.github\.io\/ENVX1002-handbook\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>