{
  "hash": "a49a0bc486bccfb6d6b90afe2962bce3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Lab 9 - Describing relationships\nembed-resources: true\nresources:\n  - data/ENVX1002_practical_data_Regression.xlsx\n---\n\n\n\n\n\n\n\n\n\n<br>\n\n::: callout-tip\n### Learning Outcomes\n\n* Calculate and interpret Correlation Coefficients in Excel and R\n* Produce scatterplots in Excel and R\n* Compare numerical and analytical model fitting methods in Excel\n* Fit simple linear models and obtain associated model summaries in R\n* Overlay fitted models onto scatterplots in R\n\n:::\n\n## Before you begin\n\nCreate your Quarto document and save it as `Lab-09.Rmd` or similar. The following data files are required:\n\n1) [ENVX1002_practical_data_Regression.xlsx](data/ENVX1002_practical_data_Regression.xlsx)\n\n<br>\n\n## Exercise 1: Linear Modelling in Excel\n\nThis exercise focusses on fitting the model parameters and demonstrating two ways a model can be fitted - numerical or analytical; \n\n* Analytical: equation(s) are used directly to find solution, e.g. estimate parameters that minimise residual sum of squares\n\n* Numerical: computer uses “random guesses” to find set of parameters to that minimises objective function, in this case\nresidual sum of squares\n\nWe mostly use R for modelling, but R does everything automatically. It is important to know what is going on 'behind the scenes', which is why we are starting in Excel. Similar to the tutorial, you will be calculating each component of the model parameter step by step in the exercises that follow. \n\n<br>\n\n### 1.1 Horses\n\nThis is our example of Analytical fitting method. \n\nThe number of horses on Canadian farms appeared to decrease after the war:\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|      |     |     |     |     |     |\n|:-----|----:|----:|----:|----:|----:|\n|year  | 1944| 1945| 1946| 1947| 1948|\n|horse |   28|   26|   22|   20|   19|\n\n\n:::\n:::\n\n\n\n\n\n\na) To see whether this is likely to be true, fit a model to the above data 'by hand' in Excel. To aid the calculation it is recommended to fill out the Excel table provided ENVX1002_practical_data_Regression.xlsx, you can find it in the spreadsheet labelled *Horses*.  \n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\nb0 = 4693.4 b1 = -2.40 SSxy = -24 SSxx = 10 mean(x) = 1946 mean(y) = 23 The table we have provided in Excel has broken the regression parameter equations (b0, b1) into smaller components so you can understand the underlying mechanisms and where these values come from.\n\n:::\n\nThe table we have provided in Excel has broken the regression parameter equations (b0, b1) into smaller components so you can understand the underlying mechanisms and where these values come from. \n\nb) Plot the two variables in Excel and fit a line. You can fit a number of models in Excel simply by right clicking on the scatter of points clicking **Add Trendline ...**.  Within the add Tendline window (see screenshot below), a number of options are given, here we want **Linear** and we want to tick **display the Equation** and **Display r-squared on the chart**.  \n\n<br>\n\n![Screenshot: Format Trendline](images/format_trendline.png)\n\n<br>\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\nShould be a nice plot in excel, equations should match your calculated b0 and b1\n\n:::\n\nThe R-squared value is a measure of how well the model fits the data where 1.0 is a perfect fit; we will discuss this more in Week 10.  The values which appear in the model equation should be the same as those obtained in your earlier calculations.  \n\nc) Although it is important for the model equation, do you think the intercept provides a realistic value in this particular case? What does it mean?\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\nThe intercept is 4693, suggesting at the year zero, Canadian farms had 4693 horses. Other than to obtain an intercept, it does not make sense to extrapolate beyond the years we have data for.\n\n:::\n\nd) Calculate the correlation coefficient using the **=CORREL** function in Excel. Type **=CORREL(** and highlight the **Year** column, and then after a comma highlight the **Horses** column and close the brackets. \n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\nr = -0.979795897, meaning there is a strong relationship in the negative direction; i.e. as the years increase, the number of horses have decreased.\n\n:::\n\ne) If the relationship was non-linear would this would be a good statistic to use to describe the relationship between horse and years? Explain your answer. \n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\nThe Pearson correlation coefficient is only useful for describing linear relationships. Based on the limited sample size we have, the scatterplot looks like a linear relationship, and so it would be ok to use the correlation coefficient in this case.\n\n:::\n\n<br>\n\n### 1.2 Fertiliser data\n\nThis is our example of numerical fitting of a model. \n\nFigure 1 shows a plot of yield against fertiliser where a linear model is fitted through the scatterplot of raw observations.  Intuitively you would draw this as a line that comes as close to possible to all observations which you may have come across as a ‘line of best fit’.  In this exercise we will explore how models can be fitted automatically based on least-squares estimation.\n\n<br>\n\n![Figure 1: Plot of Yield-response to fertiliser](images/Practical_Topic9_yieldfert.jpg)\n\n<br> \n\nIn Figure 1 you will notice that the line does not fit the data perfectly which is typical of biological and environmental data.  A measure of how far the model is from the data is the residual.\n\n\n\\begin{equation} \nresidual = y_i - \\hat{y}_1 \n\\label{1}\n\\end{equation}\n\nWhere $y_i$ is the observed value for the ith observation and $\\hat{y}_1$ is the predicted value for the *i*th observation.  In this case the predicted value is based on the linear model.\n\nIf we add up the square of the residuals for the n observations we get something called the Residual Sum of Squares ($SS_{res}$):\n\n\\begin{equation}\nSS_{res} =\\sum_{i = 1}^{n} (y - \\hat{y})^2 \\label{2} \n\\end{equation}\n\nThe best fitting model will have the smallest RSS.  The general method is called least-squared estimation.  We will now use Excel to find the optimal model.\n\nEnter values of 2 for the y-intercept ($b_0$) and 3 for the slope ($b_1$) in cells H2:H3.  These are the initial guess values.  \n\nb)\tNow use these parameter values to create predictions for each value of fertiliser in the Predicted column. \n\nMake sure that rather than writing in the value '2' and '3' for your predicted column, you refer to cells H2 and H3 (write as $H$2 and $H$3, see screenshot below).  Once you have completed the equation, you can apply the equation to the other rows by clicking on the small box at the bottom right corner of the cell and drag it down the rows.   Writing dollar signs into your references to H2 and H3 prevents your equation from moving down the row column. \n\n<br>\n\n![Screenshot of Predicted column input](images/pred_eqtn.png)\n\n<br>\n\nc)\tUse this information to calculate (i) residuals (ii) residuals^2^ (iii) RSS.\n\nd)\tCreate a plot similar to Figure 1 where the observations are plotted as symbols and the model predictions are a line.  You should have your spreadsheet set up so that if you change the values of the parameters the plotted line changes as well.  Try to fit the line manually.  This can be difficult, especially for non-linear models.\n\ne)\tFollow instructions provided in the Tutorial, or in the file [How to install Solver](https://canvas.sydney.edu.au/files/23533099/download?download_frd=1) to ensure you have Solver ready to use in Excel. \n\nOnce you have added Solver, click on the tab **Data >> Solver**, and you will see the following (see screenshot below). For **Set Objective**, you need to select the cell where your RSS value has been calculated. We wish to minimize this so we click on Min, and we do this by Changing Cells where the parameters of the model are found, in this case the y-intercept and slope. Before clicking **Solve**, make sure you can see your calculated values so you can see how your how it all changes.  \n\n<br>\n\n![Screenshot of solver with input values](images/solver.png)\n\n<br>\n\nWhen ready, click on **Solve** and it should find a solution for the minimum RSS.  Solver uses an iterative procedure to find the minimum RSS which means it successively guesses values until it finds the optimal value.  This is a numerical solution to the problem of model fitting.  \n\nYour 'SOLVED' parameters should be the same as what appears in your trendline equation. \n\n\n<br>\n\n## Exercise 2: Fitting a model in R\n\nNow we have a deeper understanding of what is going on behind the scenes, we can fit linear models in R. \n\nBefore you begin, ensure you have a project set up in your desired folder. Then open up a fresh R markdown and save the file within this folder.\n\nDon't forget to save as you go!\n\n<br>\n\n### 2.1 Have a go - Fertiliser data\n\nYou will use the fertiliser data to fit a linear model in R. As we covered fitting linear models in the Tutorial, it is now your turn to have a go at fitting the models (with some hints along the way). \n\na) Read the following code into R:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# add the data to R Studio\nfert <- c(0, 1, 2, 3, 4, 5)\nyield <- c(2, 13, 19, 18, 25, 33)\n```\n:::\n\n\n\n\n\n\n\nb) To visually identify any trends or relationships, create a scatterplot of fertiliser vs yield. From the scatterplot you see, are there any relationships or trends evident?\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a scatterplot\nplot(fert, yield)\n```\n\n::: {.cell-output-display}\n![](Lab09_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\nThe points in the scatterplot are showing a linear trend, increasing towards the top-right corner of the plot area.\n\n:::\n\nc) To numerically determine whether there is a relationship, calculate the correlation coefficient. (assume data is normally distributed). Does the correlation coefficient indicate a relationship between fertiliser and yield?\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# To calculate the correlation coefficient:\ncor(fert, yield)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9636686\n```\n\n\n:::\n:::\n\n\n\n\n\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\nThe correlation coefficient is 0.964, indicating there is a strong relationship in the positive direction; i.e. as more fertiliser is applied, the yield increases.\n\n:::\n\nd) You can now fit the model in R using the `lm()` function. Remember to tell R the name of the object you want to store it as (in this case, `model.lm <-`), then state the name of the function. The arguments within the function (i.e. between the brackets) will be `yield ~ fert`, with `yield` being the response variable and `fert` being the predictor. \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run your model\n## yield = response variable (x)\n## fert = predictor variable (y)\nmodel.lm <- lm(yield ~ fert)\n\n# Obtain model summary - In here you can obtain the model parameters\n# Look for Intercept Estimate and fert Estimate\nsummary(model.lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = yield ~ fert)\n\nResiduals:\n     1      2      3      4      5      6 \n-2.762  2.810  3.381 -3.048 -1.476  1.095 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)   \n(Intercept)   4.7619     2.2778   2.091  0.10476   \nfert          5.4286     0.7523   7.216  0.00196 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.147 on 4 degrees of freedom\nMultiple R-squared:  0.9287,\tAdjusted R-squared:  0.9108 \nF-statistic: 52.07 on 1 and 4 DF,  p-value: 0.001956\n```\n\n\n:::\n:::\n\n\n\n\n\n\ne) In the model output obtained from `summary(model.lm)` the model parameters will be listed under 'Estimate' for the intercept and 'fert'. Compare these values to what you have calculated in Excel. \n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\nIntercept = 4.7619 = $b_0$ fert = 5.4286 = $b_1$ These coefficients should be the same as those calculated in Excel.\n\n:::\n\nf) Based on this output, what would the model equation be? Does it match your findings in Excel?\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\nSubstituting in parameters from R output:\n\n$$\nYield = 4.7619 + 5.4286fert\n$$\n\nThis should be the same as the equation obtained in Excel\n\n:::\n\ng) You can now fit your model to the scatterplot you created previously using the `abline()` function. Make sure you run the plot function and the abline function in one go. If the lines are run separately, an error may appear saying \"plot.new hasn't been called yet\"; this is because the abline function requires a current plot on which it can overlay the line. \n\nAlso remember, when presenting plots (e.g. in a report), they should be able to stand alone and be self-explanatory. We therefore need to make sure there are clear axis labels. This can be done using 'xlab' and 'ylab' arguments. \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add the linear model to your scatterplot\nplot(fert, yield, xlab = \"fertiliser applied\", ylab = \"Yield\")\nabline(model.lm, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](Lab09_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n<br>\n\n### 2.2 ABARES data \n\nIn this final example we will be using a dataset obtained from the Australian Bureau of Agricultural and Resource Economics and Sciences  ([ABARES](https://www.agriculture.gov.au/abares)). The dataset provides a measure of productivity growth (TFP; Total Factor Productivity) in the Australian dairy industry from the years 1978 to 2018.    \n\nMore information about the ABARES dataset and productivity can be found [here](https://www.agriculture.gov.au/abares/research-topics/productivity/agricultural-productivity-estimates#dairy ).\n\na) Read in the data from the Excel file for today's practical. \n\nBecause we have such a large dataset this time, it is better to read the data straight from Excel than read in each individual value. Reading straight from the source file in Excel saves time and reduces chance of input error. \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\n\nABARES <- read_excel(\"data/ENVX1002_practical_data_Regression.xlsx\", sheet = \"ABARES\")\n```\n:::\n\n\n\n\n\n\nb) Create a scatterplot of `Year` against `TFP`. Dont forget the format will be different now - instead of only mentioning the object name, e.g. plot(yield, fert), you will need to refer to the specific columns within the ABARES dataset. (i.e. ABARES$Year).\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(ABARES$Year, ABARES$TFP)\n```\n\n::: {.cell-output-display}\n![](Lab09_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n:::\n\nc) Can you see a trend between TFP and Year? Or are the points evenly scattered?\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\nThere seems to be an overall positive trend in the plot\n\n:::\n\nd) Calculate the correlation coefficient between these two variables. Is there a strong relationship?\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(ABARES$Year, ABARES$TFP)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9166122\n```\n\n\n:::\n:::\n\n\n\n\n\n\nThe correlation coefficient is 0.917, indicating a strong relationship in the positive direction. This means there has been positive growth in the dairy industry over time.\n\n:::\n\ne) Fit a model to your data and obtain the model summary. Year will be our predictor and TFP will be our response variable. What are the model parameters (i.e. $b_0$ and $b_1$)?\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Fit linear model\nabares.lm <- lm(TFP ~ Year, data = ABARES)\n\n#Model summary\nsummary(abares.lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = TFP ~ Year, data = ABARES)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-17.9166  -4.7782   0.9115   6.3601  12.7159 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -2998.0129   218.1369  -13.74   <2e-16 ***\nYear            1.5632     0.1092   14.32   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 8.271 on 39 degrees of freedom\nMultiple R-squared:  0.8402,\tAdjusted R-squared:  0.8361 \nF-statistic:   205 on 1 and 39 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n\n\nBased on the model summary output, our parameters are:\n\n$b_0$ = -2998.0129 $b_1$ = 1.5632\n\n:::\n\nf) What would the equation for this model be?\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\nUse the coefficients from above and substitute into lm equation:\n\n$$\nTFI = -2998.0 + 1.5632Year\n$$\n\n:::\n\ng) Overlay your model onto the scatterplot you produced earlier. When plotting make sure you refer to the column names as you did for the model (e.g. ABARES$Year).\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(ABARES$Year, ABARES$TFP, xlab = \"Year\", ylab = \"Total factor productivity of Dairy (TFP)\")\nabline(abares.lm, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](Lab09_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n:::\n\n<br>\n\nThat's it! Great work today. Next week: interpreting linear models!\n\n# Bonus take home exercises\n\n## Exercise 1: Cars stopping distance\n\nFor this exercise we willuse the inbuilt dataset cars to see if there is a relationship between a cars speed (mph) and stopping distance (fft).\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(cars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  speed dist\n1     4    2\n2     4   10\n3     7    4\n4     7   22\n5     8   16\n6     9   10\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\na) Create a scatterplot of speed vs distance\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(cars$speed, cars$dist)\n```\n\n::: {.cell-output-display}\n![](Lab09_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n:::\n\nb) Is there are trend? Or are the point evenly scatered? \n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\nThere is a positive relationship between speed and distance.\n\n:::\n\nc) Calculate the correlation coefficient between these two variables. Is there a strong relationship?\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(cars$speed, cars$dist)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8068949\n```\n\n\n:::\n:::\n\n\n\n\n\n\nThe correlation coefficient is 0.8, which indicates a very strong positive relationship\n\n:::\n\nd) Fit a model to your data and obtain the model summary.\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncars_lm <- lm(dist~ speed, data = cars)\n\nsummary(cars_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = dist ~ speed, data = cars)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-29.069  -9.525  -2.272   9.215  43.201 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -17.5791     6.7584  -2.601   0.0123 *  \nspeed         3.9324     0.4155   9.464 1.49e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 15.38 on 48 degrees of freedom\nMultiple R-squared:  0.6511,\tAdjusted R-squared:  0.6438 \nF-statistic: 89.57 on 1 and 48 DF,  p-value: 1.49e-12\n```\n\n\n:::\n:::\n\n\n\n\n\n\n$b_0$ =  -17.5791  \n$b_1$ = 3.9324\n\n:::\n\ne) What would the equation of the line be?\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\nDistance = 3.9324*Speed -17.5791\n\n:::\n\nf) Overlay your model onto the scatterplot you produced earlier\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(cars$speed, cars$dist)\nabline(cars_lm, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](Lab09_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n:::\n\n## Exercise 2: Penguins\n\nFor this exercise, we will be using the palmer penguin data set to see if there is a relationship between bill and flipper length.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Load libraries\nlibrary(palmerpenguins)\nlibrary(tidyverse)\n\n#Clean data\npenguins <- penguins%>%\n  na.omit()#remove missing data\n\nhead(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n  species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g\n  <fct>   <fct>              <dbl>         <dbl>             <int>       <int>\n1 Adelie  Torgersen           39.1          18.7               181        3750\n2 Adelie  Torgersen           39.5          17.4               186        3800\n3 Adelie  Torgersen           40.3          18                 195        3250\n4 Adelie  Torgersen           36.7          19.3               193        3450\n5 Adelie  Torgersen           39.3          20.6               190        3650\n6 Adelie  Torgersen           38.9          17.8               181        3625\n# ℹ 2 more variables: sex <fct>, year <int>\n```\n\n\n:::\n:::\n\n\n\n\n\na) Create a scatterplot of bill length vs flipper legth\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(penguins$bill_length_mm, penguins$flipper_length_mm)\n```\n\n::: {.cell-output-display}\n![](Lab09_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n:::\n\nb) Is there are trend? Or are the point evenly scatered? \n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\nThere is a positive trend\n\n:::\n\nc) Calculate the correlation coefficient between these two variables. Is there a strong relationship?\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(penguins$bill_length_mm, penguins$flipper_length_mm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6530956\n```\n\n\n:::\n:::\n\n\n\n\n\n\nThe correlation coefficient is 0.65, ehich indicates a medium- positive relationship.\n\n:::\n\nd) Fit a model to your data and obtain the model summary. What are the parameters?\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguin_model<- lm(bill_length_mm ~ flipper_length_mm, data = penguins)\n\nsummary(penguin_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = bill_length_mm ~ flipper_length_mm, data = penguins)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8.6367 -2.6981 -0.5788  2.0663 19.0953 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       -7.21856    3.27175  -2.206    0.028 *  \nflipper_length_mm  0.25482    0.01624  15.691   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.148 on 331 degrees of freedom\nMultiple R-squared:  0.4265,\tAdjusted R-squared:  0.4248 \nF-statistic: 246.2 on 1 and 331 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n\n\n$b_0$ = -7.21856  \n$b_1$ = 0.25482\n\n:::\n\ne) What would the equation of the line be?\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\nbill length = -7.21856  + 0.25482* flipper length\n\n:::\n\nf) Overlay your model onto the scatterplot you produced earlier\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(penguins$bill_length_mm, penguins$flipper_length_mm)\nabline(penguin_model, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](Lab09_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n:::\n\n## Exercise 3: Old Faithful Geyser Data\n\nFor this exercise, we will be looking at the relationship between geyser eruption time and time between erupttions, using the inbuilt data set faithful\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(faithful)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  eruptions waiting\n1     3.600      79\n2     1.800      54\n3     3.333      74\n4     2.283      62\n5     4.533      85\n6     2.883      55\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\na) Create a scatterplot of eruptions vs waiting time\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(faithful$waiting, faithful$eruptions)\n```\n\n::: {.cell-output-display}\n![](Lab09_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n:::\n\nb) Is there are trend? Or are the point evenly scatered? \n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\nThere is a positive relationship between eruptions length and waiting time\n\n:::\n\nc) Calculate the correlation coefficient between these two variables. Is there a strong relationship?\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(faithful$eruptions, faithful$waiting)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9008112\n```\n\n\n:::\n:::\n\n\n\n\n\n\nThe correlation coefficient is 0.9, which indicates a very strong positive relationship\n\n:::\n\nd) Fit a model to your data and obtain the model summary.\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfaithful_lm <- lm(eruptions~ waiting, data = faithful)\n\nsummary(faithful_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = eruptions ~ waiting, data = faithful)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.29917 -0.37689  0.03508  0.34909  1.19329 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -1.874016   0.160143  -11.70   <2e-16 ***\nwaiting      0.075628   0.002219   34.09   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4965 on 270 degrees of freedom\nMultiple R-squared:  0.8115,\tAdjusted R-squared:  0.8108 \nF-statistic:  1162 on 1 and 270 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n\n\n$b_0$ = -1.874016 \n$b_1$ = 0.075628\n\n:::\n\ne) What would the equation of the line be?\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\neruptions =  0.075628* waiting -1.874016 \n\n:::\n\nf) Overlay your model onto the scatterplot you produced earlier\n\n::: {.content-visible when-profile=\"solution\"}\n### Solution {style=\"color:green;\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(faithful$waiting, faithful$eruptions)\nabline(faithful_lm, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](Lab09_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n:::\n\n<br>\n<br>\n<!--The code below reduces white space at the end of the output doc-->\n<div class=\"tocify-extend-page\" data-unique=\"tocify-extend-page\" style=\"height: 0;\"></div>",
    "supporting": [
      "Lab09_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}